### ISSUE TITLE
Add option to disable getting git information

### ISSUE THREAD

**Issue by qinezh** [dotnet/docfx#1004]

**Comment by agc93** [comment]
Isn't this what the `_disableContribution` global metadata option does? The [properties documentation](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html?q=_app#32-properties-for-build) certainly implies it does:

|Name|Description|
|:------|:------------|
|_disableContribution|Indicate whether to show the View Source and Improve this Doc buttons.|

Or does that option only disable the buttons, rather than the actual logic in the generation?

**Comment by qinezh** [comment]
Yes, you're right. I changed the title to avoid confusion.

**Comment by qinezh** [comment]
no need for now. Closed.

**Comment by fredrikeriksson** [comment]
@qinezh I believe you should consider reopening this as projects that's not using Git will get a lot of exceptions which drastically increases time spent in metadata phase and also in build time to some degree. I assume that the same applies if Git isn't installed on the machine.
