### ISSUE TITLE
"ASP.NET website project template" in "Getting Started" is wrong

### ISSUE THREAD

**Issue by grokys** [dotnet/docfx#135]
The "Getting Started" docs say to use "ASP.NET website project template" but that exact project type doesn't exist in my VS2015.

Do you mean "ASP.NET Web Application"? It would be helpful to specify the correct name, as it's confusing otherwise.

Also, the docs imply that it's *optional* to use that project template. If I *don't* use that project template,what should I use?

**Comment by vicancy** [comment]
"ASP.NET website project template" no longer exists, for Empty "ASP.NET Web Application", it requires additional steps to generate the website. I will update the documentation for that e2e flow.

For the second question: you can use whatever project template, e.g. ConsoleApplication. Create a ConsoleApplication1, add a new **public** class into it, and build. `_site` folder will be generated under folder *ConsoleApplication1*. The difference with *ASP.NET* project is that ConsoleApplication does not have `preview` functionality so that you need to use other tools such as `IIS`, `http-server` from node.js to host and preview your `_site`.

**Comment by dalenewman** [comment]
At least for me, things didn't work out when I used an ASP.NET Web Application with an *ASP.NET 5 Empty* template. I retried with the *ASP.NET 4 Empty* template it worked fine.

**Comment by vicancy** [comment]
Should work now with the latest v1.7
