### ISSUE TITLE
Any way to populate example tags from source code?

### ISSUE THREAD

**Issue by madelson** [dotnet/docfx#1579]
Note: this is a feature request. It's possible that this functionality already exists, and I just haven't been able to figure it out. If so, please point me to the appropriate part of the documentation and close!

I've been setting up docfx for a project, and one of the things I find most valuable is how you can use example and code tags to create syntax-highlighted code examples in the docs.

For most people quickly reading through, this is far more useful than a block of text.

However, writing code within code tags is a pain (e. g. having to encode "<" and ">"). Aside from that, there's no guarantee that the code compiles and stays functional as changes are made!

What I'd love to be able to do is write my sample code directly in a source file (e. g. in a tests or samples project) and then link it such that docs would pull it in. For example:

```
/// ...
/// <example>
/// You can perform bulk updates on <see cref="ImmutableList{T} /> using a builder:
// <code><see cref="ImmutableListSamples.Builder" /></code> (not sure what the syntax should be)
/// </example>
public class ImmutableList<T>
{
    ...
}

...

internal class ImmutableListSamples
{
    void Builder()
    {
        // start with an ImmutableList<T>
        var list = ImmutableList.CreateRange(new[] { 1, 2, 3 });

        // create a builder for the list
        var builder = list.ToBuilder();

        // the builder can be used as a mutable IList<T>
        builder.RemoveAt(0);
        Console.WriteLine(builder.Count); // 2

        // when you're done modifying, convert back using ToImmutable()
        var newList = builder.ToImmutable();
    }
}
```

I'd want the docs to recognize the use of a cref in a code tag and inline the code text into that tag. So that the sample appears directly on the API docs page for ImmutableList.

**Comment by LordZoltan** [comment]
Docfx has this feature generally in .md files - see 'Code Snippets' in [this documentation](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html)

I've used it for my project - see [this .md file](https://github.com/ZolutionSoftware/Rezolver/blob/master/doc/Rezolver.Documentation/_docfx_proj/docs/index.md) for an example of whole-file inclusion (search for 'ObjectTargets.cs') and the [live version here](http://rezolver.co.uk/developers/docs/index.html#matching-an-example-to-a-test).  If you browse the other docs and their .mds you'll see how to use queries to include bookmarked sections of source code instead of the whole file.

Now, since markdown is supported in XMLDoc, I'm guessing that you can try to repeat this same technique to see if the examples you want appear in the API documentation?

**Comment by vicancy** [comment]
Thanks Lord, totally agree with you 😄

**Comment by LordZoltan** [comment]
😃 Am glad I was right!  (Now I have to start using this rather excellent functionality myself!)
