### ISSUE TITLE
Why is DFM based on GFM rather than CommonMark?

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/docfx#168]
[CommonMark](http://commonmark.org/) has the support of GitHub and seems to be the way forward. What made you opt for GFM as a base?

**Comment by chenkennt** [comment]
We chose GFM mainly because it's default language for writing on github. The learning curve will be smoothe is user is already familiar with how to write on github.

**Comment by vwxyzh** [comment]
We open the markdown engine now, you can switch to any markdown engine in plug-in by implements this [interface](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.Plugins.IMarkdownServiceProvider.html#Microsoft_DocAsCode_Plugins_IMarkdownServiceProvider), and set the name of markdown engine in docfx.json or in command-line arguments.

**Comment by stijnherreman** [comment]
@vwxyzh Nice! Thank you for the update.

**Comment by john-cj** [comment]
> We open the markdown engine now, you can switch to any markdown engine

Yes, we can, but DFM have some [unique features](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html).

On the other hand, Commonmark is more stable and standardized then GFM.

> The learning curve will be smoothe is user is already familiar with how to write on github.

The learning curve will be the same. No difference at all. Commonmark just fix some edge-cases, nothing more. For novice users it will be the same.

For advanced markdown users, however, Commonmark is more prefereble, because it is an attempt to create a standard and it really fix some edge-case issues.

It will be amazing, to see DFM is based on commonmark rather then GFM. As I said, there no pitfails, only wins for all users.
