### ISSUE TITLE
Hard-to-diagnose "No metadata is generated"

### ISSUE THREAD

**Issue by matkoch** [dotnet/docfx#1686]
In relation to #165.

Even though I have `--logLevel Verbose` I cannot tell why the project is being skipped with `Warning:No metadata is generated for XXX.`.

**Comment by vicancy** [comment]
1. Better logging
2. Troubleshooting guide

**Comment by ThadHouse** [comment]
Is there anything else we can try rather than just install MS Build Tools 2015? I have multiple systems that have both 2015 and 2017 installed, and still can't generate metadata. I don't think that is the only dependency, or maybe something in VS 2017 is overriding something in the GAC causing docfx to fail.

**Comment by matkoch** [comment]
@ThadHouse in my case I was targeting multiple target frameworks. In case you have the same, you need to specify them in your docfx.json as described here: https://github.com/dotnet/docfx/issues/1254#issuecomment-294080535

**Comment by ThadHouse** [comment]
I'll double check that, but I think I've tried that before. I'm getting the error where no files are being returned by the MSBuildProject. But I'll try again. I might just end up putting a project.json back in my projects, because that does seem to actually wor.

**Comment by matkoch** [comment]
What do you have instead? I think I've read something about xproj not being supported. But not sure :)

**Comment by ThadHouse** [comment]
I'm using new VS 2017 csproj files, which have never worked for me in docfx, even though theyre supposed to.

**Comment by matkoch** [comment]
Yes, for me that works. Public types/members? Maybe you can reference the project?

**Comment by ThadHouse** [comment]
Yeah I've tried a ton of different things. Even example projects posted by both the docfx team, and other people that have posted issues don't work for me. Nothing related to the new csproj works for me.

**Comment by ThadHouse** [comment]
I was able to get it working on one of my machines (I don't know how...) However, AppVeyor still does not work for me, so something still is not right with the dependencies that are thought to be required.

**Comment by vicancy** [comment]
Hi ThadHouse, could you share your project & AppVeyor settings, to allow me to take a look?

**Comment by ThadHouse** [comment]
https://github.com/robotdotnet/WPILib-Docs/tree/metadatatest

Here's my repo that I have to generate the docs. The runBuild.ps1 script downloads the latest version of docfx, clone my repos, and then attempt to run docfx. The appveyor settings are in appveyor.yml. 

https://github.com/robotdotnet/FRC-Utilities

This is probably my easy repo to test metadata generation if you want to try manually, since there isn't a lot in the repo, and only 2 targetplatforms.

**Comment by ThadHouse** [comment]
https://ci.appveyor.com/project/robotdotnet/wpilib-docs/build/master-35-qxdglprl

Here's also the latest build attempt on AppVeyor

**Comment by vicancy** [comment]
Hi @ThadHouse According to https://github.com/robotdotnet/FRC-Utilities you are targeting multiple frameworks, could you add 
```json
"properties": {
                "TargetFramework": <one_of_your_framework>
            }
```
to your metadata section?

**Comment by ThadHouse** [comment]
Neither the TargetFramework nor the updated build tools requirement help this build on appveyor. Also tested the new logger function, and all it says is "Failed to parse file", so its not very helpful.
