### ISSUE TITLE
Does the toc.html.tmpl need header, scripts and footer?

### ISSUE THREAD

**Issue by MichaCo** [dotnet/docfx#175]
While adjusting the default template to my own needs, I found that the TOC actually contains a bunch of html which is not needed at all: Full header, scripts and footer. 
The `loadToc` JavaScript strips all that out anyways, so the question is, why is it in the template in the first place?

I know, its minor, but would still be an improvement in loading time/traffic eventually.

Actually, all what is needed is the following I think:
```html
<div class="sidetoggle collapse" id="sidetoggle">
    <div>
        <div class="sidefilter">
			<form class="toc-filter">
				<span class="glyphicon glyphicon-filter filter-icon"></span>
				<input type="text" id="toc_filter_input" placeholder="Enter here to filter..." onkeypress="if(event.keyCode==13) {return false;}">
			</form>
        </div>
        <div class="sidetoc">
			<div class="toc" id="toc">
				{{^leaf}}
				{{>partials/li}}
				{{/leaf}}
			</div>
        </div>
    </div>
</div>
```
Or is this page used somewhere else?

**Comment by vicancy** [comment]
Hi @MichaCo, thanks for the feedback.
Header, footer and scripts are added to `toc.html` with the consideration that: when someone accidentally navigates to `toc.html`, he/she sees a normal web page with a consistent style. After all, `toc.html` does exist.
One idea is to generate `toc.json` instead of `toc.html` to keep the content minimum.
Actually we are thinking of embedding TOC/navbar into the html page when `docfx build` instead of ajax loading a TOC file from client `js`. However, this change requires some changes in DocFX Template Rendering system, and we are still working on settle down the design.

**Comment by MichaCo** [comment]
sounds good :+1:

**Comment by chenkennt** [comment]
we have a static toc template now.
