### ISSUE TITLE
the default template used for generating PDFs is way too basic for API-Docs

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#1833]
### Title
The default template used for generating PDFs is way too basic for API documentation.

### Functional impact
It forces literally everyone who wants to ship API documentation as PDF to write a custom template. The default one is not good enough for anyone.

### Minimal repro steps
run `docfx pdf` on any site that has API documentation.

### Expected result
A PDF is generated that looks halfway decent.

### Actual result
A PDF is generated that looks like this (example page for API-docs of some methods of a class):
![capture](https://user-images.githubusercontent.com/418030/27864365-89b4eda0-618e-11e7-8759-833d504f3f97.PNG)

**Comment by vicancy** [comment]
Hi @bitbonk could you provide more details about "way too basic"? What features are you expecting?
PDF uses a similar template as docs.microsoft.com, for example https://docs.microsoft.com/en-us/dotnet/api/microsoft.csharp.runtimebinder?view=netcore-1.1.
PDF is in its very early stage, we are open to any feature proposals. 
Besides, you mention that you need to "write a custom template" when shipping PDF, it would be great if you can *share* your template with us, through PR or share it in http://dotnet.github.io/docfx/templates-and-plugins/templates-dashboard.html so that others don't have to "write a custom template" anymore. 😄

**Comment by vicancy** [comment]
Your screenshot shows almost no style to the PDF, are you generating from the latest version? mine is quite different, it at least contains some style..
[docfx-seed_pdf.pdf](https://github.com/dotnet/docfx/files/1126818/docfx-seed_pdf.pdf)
![image](https://user-images.githubusercontent.com/668244/27896843-14199bb0-624f-11e7-85c8-6e710e33641f.png)

**Comment by bitbonk** [comment]
I am sorry, this is totally my fault, I had an empty `default.css` in custom template that was referenced in `docfx.json`. This issue can be closed.
