### ISSUE TITLE
Mono not working from 2.18.3 "Operation is not supported on this platform"

### ISSUE THREAD

**Issue by vicancy** [dotnet/docfx#1856]
" Operation is not supported on this platform" error occurs when `mono docfx docfx-seed/docfx.json`, the root cause is: docfx is trying to use "Microsoft.Net.Compilers" csc.exe to compile instead of mono's mcs, "Microsoft.Net.Compilers" is introduced in 2.18.3 to remove the dependency to Build Tool 2015...

**Comment by vicancy** [comment]
I would suggest generating metadata from assemblies instead of source code as a workaround:
```json
"metadata: [
   {
       "src": "target/**.dll",
       "dest": "api"
   }
]
```

**Comment by Dids** [comment]
Thank you for the workaround, can confirm it allows me to get a bit further.

Before I open another issue, do you happen to know if this is also related:

```
[17-07-11 10.32.37.563]Error:System.AggregateException: One or more errors occurred. ---> System.NotImplementedException: The method or operation is not implemented.
  at Newtonsoft.Json.Linq.JObject.System.Collections.Generic.IDictionary<System.String,Newtonsoft.Json.Linq.JToken>.get_Values () [0x00000] in <607e95f78559498690f968784b884761>:0 
```

I've been wrestling with trying to get DocFX to play nice with macOS/Mono as well as .NET Standard 1.6/2.0 libraries, but so far haven't had much luck.

The exception above is happening on Windows too, so I'm not sure if I should open a separate issue for it or if it's simply due to DocFX not supporting .NET Standard in any way yet.

**Comment by vicancy** [comment]
@Dids Never encountered this error before, DocFX should not have trouble supporting .NET standard. Please open an issue for that.

**Comment by vicancy** [comment]
Opened an issue in https://github.com/dotnet/roslyn/issues/20848 to track it

**Comment by Dids** [comment]
@vicancy Thanks, opened a [new issue](https://github.com/dotnet/docfx/issues/1863) for the exception and also discovered a temporary workaround for it.

**Comment by Dids** [comment]
@vicancy When generating documentation from the assemblies, are there any workarounds for also including XML comments?
