### ISSUE TITLE
What happened to "jsref" plugin?

### ISSUE THREAD

**Issue by tintoy** [dotnet/docfx#2218]
Hi - it looks to me like the `jsref` plugin was removed in #2178.

Has this moved somewhere else, or is it no longer supported? If it's no longer supported, is there an alternative for getting JavaScript reference docs into DocFX?

**Comment by vicancy** [comment]
Hi @tintoy are you using `jsref` plugin currently?

**Comment by tintoy** [comment]
I was about to start using it - we've used typedoc with a converter for Typescript but it doesn't like plain JS... :)

**Comment by tintoy** [comment]
Is it being removed because nobody was using it?

**Comment by vicancy** [comment]
We are consolidating different languages into going through one UniversalDocumentProcessor, including TypeScript(https://github.com/docascode/type2docfx), JavaScript(https://github.com/docascode/Node2DocFX), and Python(https://github.com/docascode/sphinx-docfx-yaml)... The only thing missing now is a default template... which @superyyrrzz is focusing on currently... 
And yes, `jsref` is removed because no one is using it and actually it is out-of-maintenance..

**Comment by tintoy** [comment]
Ah missed the Node one, that'll do nicely! Thanks :)

**Comment by vicancy** [comment]
Create a task for this https://github.com/dotnet/docfx/issues/2218
