### ISSUE TITLE
Issues with extension methods defined on types with the same full name (but different assembly qualified name)

### ISSUE THREAD

**Issue by danroth27** [dotnet/docfx#231]
In ASP.NET we often define extension methods for the same type in multiple assemblies. The extension methods are by convention defined on static classes with the same name and namespace (but different assembly). For example, we have many assemblies that define extension methods for the ServiceCollection type. These extension methods all live on classes called Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions. DocFX produces the following warnings in these cases:

```
Warning: Duplicate member Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions is found from aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs and aspnet/antiforgery/src/Microsoft.AspNet.Antiforgery/ServiceCollectionExtensions.cs, use the one in aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs and ignore the one from aspnet/antiforgery/src/Microsoft.AspNet.Antiforgery/ServiceCollectionExtensions.cs

Warning: Duplicate member Microsoft.AspNet.Hosting.HostingEnvironmentExtensions is found from aspnet/hosting/src/Microsoft.AspNet.Hosting.Abstractions/HostingEnvironmentExtensions.cs and aspnet/hosting/src/Microsoft.AspNet.Hosting/HostingEnvironmentExtensions.cs, use the one in aspnet/hosting/src/Microsoft.AspNet.Hosting.Abstractions/HostingEnvironmentExtensions.cs and ignore the one from aspnet/hosting/src/Microsoft.AspNet.Hosting/HostingEnvironmentExtensions.cs

Warning: Duplicate member Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions is found from aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs and aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, use the one in aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs and ignore the one from aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection/ServiceCollectionExtensions.cs

Warning: Duplicate member Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions is found from aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs and aspnet/routing/src/Microsoft.AspNet.Routing/ServiceCollectionExtensions.cs, use the one in aspnet/dependencyinjection/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs and ignore the one from aspnet/routing/src/Microsoft.AspNet.Routing/ServiceCollectionExtensions.cs

Warning: Duplicate member Microsoft.AspNet.DataProtection.DataProtectionExtensions is found from aspnet/dataprotection/src/Microsoft.AspNet.DataProtection.Abstractions/DataProtectionExtensions.cs and aspnet/dataprotection/src/Microsoft.AspNet.DataProtection.Extensions/DataProtectionExtensions.cs, use the one in aspnet/dataprotection/src/Microsoft.AspNet.DataProtection.Abstractions/DataProtectionExtensions.cs and ignore the one from aspnet/dataprotection/src/Microsoft.AspNet.DataProtection.Extensions/DataProtectionExtensions.cs
```

I believe if extension methods are documented on the type that they extend (like MSDN does today) then this really shouldn't be an issue.

**Comment by hugufc** [comment]
Hi,

I think that the same occurs in shared project code referenced in multiple projects.

**Comment by vicancy** [comment]
Considering merging them instead

**Comment by Shazwazza** [comment]
This is basically the same issue as this https://github.com/dotnet/docfx/issues/2041 (better description here https://github.com/dotnet/docfx/issues/2041#issuecomment-635436921) where it's not possible to have the same namespace in different projects since a namespace is a UID and it must be unique. So let's say you had "MyProject.Extensions" as a namespace with classes in it between 2 or more projects this will break a lot of things: navigation/toc/breadcrumbs will not work and behave strangely, overwrite files won't work for namespaces since it will just overwrite the 'last' one. We have an [open issue on the Lucene.Net project](https://github.com/apache/lucenenet/issues/282#issuecomment-636592141) where we're trying to come up with any solution but am getting close to exhausting all ideas. Any tips, hints, suggestions, etc... would be very much appreciated.

**Comment by iJungleboy** [comment]
Same problem here, very frustrating. 
Have some classes in a namespace in one project, and must add more classes to the same namespace in another project. 

Docfx just fails. This is IMHO terrible and is such a common thing to do that it must be supported.

**Comment by bitbonk** [comment]
Same problem here too. It seems that _docs.microsoft.com_ now does have a way to handle this. Maybe because they already use docfx v3 that might have a solution for this. Maybe, we just don't know. @danroth27 can you tell us how you solved this problem or point us to someone who knows this?

One example: 
There `SignalRDependencyInjectionExtensions` in [Microsoft.AspNetCore.SignalR.Core](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/SignalR/server/Core/src/SignalRDependencyInjectionExtensions.cs) as well as in [Microsoft.AspNetCore.SignalR](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/SignalR/server/SignalR/src/SignalRDependencyInjectionExtensions.cs) 
The Docs list both under the same Site: [Doku](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.signalrdependencyinjectionextensions?view=aspnetcore-5.0)

And it seems to be even the same UID: 

`GET https://xref.docs.microsoft.com/query?uid=Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions`

returns

```json
[
  {
    "uid": "Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions",
    "name": "SignalRDependencyInjectionExtensions",
    "fullName": "Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions",
    "href": "https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.signalrdependencyinjectionextensions",
    "schemaType": "NetType",
    "monikerGroup": "213dbee6db41b1f9ab7b8780fdfeb104",
    "commentId": "T:Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions",
    "monikers": [
      "aspnetcore-2.1",
      "aspnetcore-2.2",
      "aspnetcore-3.0",
      "aspnetcore-3.1",
      "aspnetcore-5.0",
      "aspnetcore-6.0"
    ],
    "nameWithType": "Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions",
    "type": "class",
    "summary": "<p>Extension methods for setting up SignalR services in an <a href='/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection'>IServiceCollection</a>.</p>\n",
    "tags": [
      "/dotnet",
      "public"
    ]
  }
]
```

**Comment by rickbrew** [comment]
Same issues is affecting me when trying to generate documentation for Paint.NET SDK/API. I have (for example) a class called `PaintDotNet.Direct2D1.DeviceContextExtensions` in 4 assemblies, each providing extensions for a different layer of functionality. It is not possible to change these class names now because plugins are already making use of them, and I'm not willing to break binary compatibility for the sake of documentation generation. However, plugin developers need documentation ... so it's a vicious cycle!

**Comment by Thraka** [comment]
@yufeih In 3 years this issue will be a decade old. Is it *really* going to be addressed? I need to move out of docfx if docfx can't handle these common scenarios. Why is there an ms internal docfx that has all these things the public is asking for? Once v3 split and went internal, it kind of signaled the death of docfx.

**Comment by rickbrew** [comment]
> Is it _really_ going to be addressed?

imo, I doubt it :)

I ended up using [il-repack](https://github.com/gluck/il-repack) to merge all of my assemblies, and then I generate docs from the merged DLL.

Every docs page is attributed to the merged DLL instead of the individual DLLs, but that is OK for my scenario.

Example: 
- https://paintdotnet.github.io/apidocs/api/PaintDotNet.Direct2D1.Direct2DFactoryExtensions.html
- https://paintdotnet.github.io/apidocs/api/PaintDotNet.Direct2D1.DeviceContextExtensions.html

**Comment by yufeih** [comment]
@Thraka @rickbrew

This is addressed in 2.70.4 release. Let me know if things aren't working otherwise.

**Comment by Thraka** [comment]
Thanks @yufeih !

**Comment by rickbrew** [comment]
> @Thraka @rickbrew
> 
> This is addressed in 2.70.4 release. Let me know if things aren't working.

Wow! I will go test this right now :)

**Comment by rickbrew** [comment]
It works 👍 The methods have the right assembly attribution:

![image](https://github.com/dotnet/docfx/assets/10873410/34c3541d-6fd0-435c-9c5d-4fa3cde1d0f5)

The class itself seems to just pick one of the assemblies to be attributed to. I'm not sure if it's the "topmost" or "bottommost" assembly in the dependency graph, or effectively random (maybe dictated by hashtable organization).

![image](https://github.com/dotnet/docfx/assets/10873410/a5f6f8a6-7736-46ad-a083-c43d1fe37b87)

I don't know what happens if there are two overloads of the same method name that are in two separate assemblies (e.g. what if I had another `CreateBitmap` overload somewhere else?). (Because all of the method overloads show up on the same page)

I'd love to see either 1) all of the assemblies listed, or 2) none of them. Maybe I can get the 2nd option to work with a template change.

In any event, this is fantastic, thanks so much @yufeih !

(screenshots above are from https://paintdotnet.github.io/apidocs/api/PaintDotNet.Direct2D1.DeviceContextExtensions.html )

**Comment by yufeih** [comment]
> The class itself seems to just pick one of the assemblies to be attributed to
We could update this to include all assembly names sorted alphabetically.

> I don't know what happens if there are two overloads of the same method name that are in two separate assemblies
They should both appear if the method signature differs.

**Comment by yufeih** [comment]
> The class itself seems to just pick one of the assemblies to be attributed to

Fixed in ApiPage output.
