### ISSUE TITLE
DocFx doesn't take <include> tag into account.

### ISSUE THREAD

**Issue by r-rc-christopher** [dotnet/docfx#2328]
**DocFX Version Used**:  2.28.3

**Template used**: default

**Steps to Reproduce**:

1. Create a "documentation.xml" file at the root of project.

```
<?xml version="1.0" encoding="utf-8" ?>
<Documentation>
  <MyClass>
    <MyMethod>
      <remarks>
        One remark
      </remarks>
    </MyMethod>
  </MyClass>
</Documentation>
```

2. Add the tag <include> on the top of a method.

```
/// <summary>
/// This method should do something...
/// </summary>
/// <include file='../Documentation.xml' path='Documentation/MyClass/MyMethod/*'/>
public void OneMethod()
{

}
```

3. Compile documentation

**Expected Behavior**:

The Remarks topic should be displayed on the documentation page. 

**Actual Behavior**:

The Remarks topic doesn't appear. 

Is the <inlude> tag supported by DocFx ?

**Comment by vicancy** [comment]
This is not supported for now.

**Comment by smaillet** [comment]
Will this ever be supported? It's a blocker for a project I'm working on. I'm unclear on how this isn't supported since the C# compiler is what processes the include to produce the final doc comments .xml for an assembly at compile time - so why does docfx get in the middle of things to actively block this?

**Comment by KalleOlaviNiemitalo** [comment]
DocFX is able to extract the metadata and documentation of your APIs in two ways:
- From source files via the Roslyn API. Maybe it does not support the `include` element in this case.
- From EXE/DLL and XML files generated by the compiler. I believe the `include` element will work in this case, because the compiler has already processed it.

**Comment by Konard** [comment]
Please add support for it.

**Comment by KalleOlaviNiemitalo** [comment]
@Konard, add this kind of thing to docfx.json:

```json
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "src/*.dll"
          ]
        }
      ],
      "dest": "api"
    }
  ]
}
```

It finds `src/*.dll` and then automatically uses the corresponding XML files if they are in the same directory as the DLL files. <https://github.com/dotnet/docfx/blob/4f1574f0a41508486127fcdf6395e0e5fafb0dd2/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs#L340-L343>

**Comment by Transeric** [comment]
Please add support for this tag.  Otherwise, the usability of this great tool is severely diminished.  Some of us are creating API documentation where we would like to include examples (via the C# example/code tags).  Without the include tag, this is really not possible.  The code simply becomes **way** to littered...to the point of unreadability.

The tag no longer seems limited to Sandcastle.  Its now included in Microsoft's official C# documentation:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/include

This page even indicates that its **already** supported by DocFx: "_consumed by documentation tools such as DocFX and Sandcastle to produce the final documentation_".  Come on guys...how hard can this be...don't make a liar out of the MS docs :)

**Comment by KalleOlaviNiemitalo** [comment]
> Some of us are creating API documentation where we would like to include examples (via the C# example/code tags).

As a workaround, you could place the code snippets in separate source (not XML) files and use [Code Snippet syntax in DocFX Flavored Markdown](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#code-snippet). That would even let your continuous integration system test the code snippets. The Go to Definition feature of Visual Studio would not show the code snippets, but IIRC `<code>` would not look good there either.

**Comment by Transeric** [comment]
> As a workaround, you could place the code snippets in separate source (not XML) files and use Code Snippet syntax in DocFX Flavored Markdown.

@KalleOlaviNiemitalo, thank you for the suggestion.  I'll definitely keep it in mind, and most likely use it, for future projects.  Regrettably, my rather large code base already uses include tags extensively.  Finding the time or budget to go back and change them all over (to make DocFX happy)  is probably a non-starter :)

> <include> works if you make DocFX consume the compiler-generated XML like the documentation says.

Perhaps this is an option.  Could you please elaborate?  I'm not certain I understand what you're proposing.  For background, I am currently generating documentation via VS builds using the NuGet package variant of DocFX.

**Comment by KalleOlaviNiemitalo** [comment]
@Transeric, do you mean the docfx.console package? It seems to install a docfx.json file that refers to "*.csproj". As I wrote [earlier in this issue](https://github.com/dotnet/docfx/issues/2328#issuecomment-520723261), if change docfx.json to refer to *.dll or *.exe files instead (don't let DocFX see the project files and source files at all) and tell the C# compiler to generate an XML documentation file, then \<include\> should work.

**Comment by Transeric** [comment]
@KalleOlaviNiemitalo, yes the docfx.console package.  Thanks, I'll give the *.dll trick a try.  Though, I still maintain the `include` tag should "just work"...whatever input you choose.  It can't be that hard to support.

**Comment by Transeric** [comment]
First, full details in case it matters: Windows 10/VS 2019/C#, docfx.console v2.56.1 NuGet package, statictoc template.

@KalleOlaviNiemitalo, I wanted to thank you again for your suggestion about code-snippets.  This is a pretty awesome feature! 

When I included the references in markdown files, it worked great!

Then came the problem...I want to include the code snippet as a part of my API reference for a class, which is generated from XML comments.  After reading a bit, I was surprised (and psyched) to find that I can include markdown in my C# XML comments.  So, I tried the following:

`
/// [!code-csharp[Example](Example.cs)]
`

The good news is that DocFX indeed recognized the reference.  The bad news is that I got the following warning in the log file:

`
{"message":"Invalid code snippet link: 'Example.cs'.","source":"BuildCommand.BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ManagedReferenceDocumentProcessor.Build.BuildManagedReferenceDocument","file":"api/Transeric.Tabular.Attributes.BooleanSerializerAttribute.yml","date_time":"2020-07-27T16:49:51.4480835Z","message_severity":"warning","code":"codesnippet-not-found","correlation_id":"B4EB5DCD-D4CD-410F-87A3-83AA5CDD558C.2.181.1.37.14.2.921.1"}
`

I'm guessing its an issue with providing a "correct" path, but I need some help.  Here are different variations on the path that I've tried without success:

1. Path relative to the source file that contains the comment.  I figured this was most likely since its what worked in the markdown file.
2. Path relative to the project that contains the source file.
3. Path relative to the solution that contains the project that contains the source file.
4. Path relative to the documentation project.
5. Path relative to the solution that contains the documentation project.
6. Absolute (Windows) file system path (up to and including the disk).

Any ideas?  In all cases, I was careful to use "/" instead of "\\" in the path, to avoid possible markdown issues.  Did I miss a possibility above? What's the magic word? I've misplaced my secret decoder ring :)

The capabilities of the code-snippet feature and the selling points you mentioned earlier have me almost convinced its worth the huge effort of retooling all of my comments.  Though, its not worth it if I can't include a snippet on the same page as the code its documenting.

**Comment by Transeric** [comment]
@KalleOlaviNiemitalo, I wanted to thank you again for your suggestions regarding code snippets.  They were extremely helpful.  The feature is absolutely awesome!

I'm definitely going to use it.  I'm going to place the markdown for code-snippets in my C# XML comments, within the `<example>` tags.  The only real challenge was figuring out the "correct" relative path for the source file, but I've got that sorted now.  It would be nice if the DocFX documentation provided some examples of how to use `\[!code-<language>]` markup within source code and discussed the root for those relative paths.

Now, I'm down to dreading the amount of work its going to take me to re-do all of my comments, but should be worth it.
