### ISSUE TITLE
[Question] Support for XSD code generation

### ISSUE THREAD

**Issue by xxcuratorxx** [dotnet/docfx#2355]
Hi,

are there any plans to automatically create docfx documentation based on XSD files (with comments) rather than c# File (with xml comments)?

If not, would it be possible to extend docfx by custom preprocessors?

thanks for any ideas,
curator

**Comment by vicancy** [comment]
Hi @xxcuratorxx I am afraid that there is no plan for supporting XSD files... One idea to generate an YAML file from XSD following the same format as C# YAML files http://dotnet.github.io/docfx/spec/metadata_format_spec.html so that docfx can generate documentation directly from it. Another idea is to leverage SchemaDrivenProcessor http://dotnet.github.io/docfx/spec/docfx_document_schema.html#7-samples, but this requires customization from schema to template.

**Comment by xxcuratorxx** [comment]
Thanks for the hints. I will investigate the affort for implementing that.
regards,
curator
