### ISSUE TITLE
Replace Logo

### ISSUE THREAD

**Issue by zulkarnainis** [dotnet/docfx#239]
I need help, i want too replace default docfx logo, i try with create in main.js with this code 

$(function () {
  jQuery('img.svg').each(function () {
    var $img = jQuery(this);
    $img.attr('src', 'images/Logo.jpg');
  });
})

but it's not working, i need your help please.. thanks

**Comment by wekempf** [comment]
I'm not associated with this project at all, but since I recently had to figure this out myself I'll try and save them some time and help you myself. The easiest way to do this would probably be to provide your own template. This doesn't mean you have to create an entire template from scratch, though. This is documented [here](http://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html), though I'll admit that documentation did me little good until I found an example where someone else had done this. So, you can look at [my project site](http://wekempf.github.io/testify/) and the [source for it](https://github.com/wekempf/testify/tree/develop/docs). Under the template directory you'll find a partials directory where I've placed replacements for the default template/theme.  You don't have to replace every partial. To replace just the logo you could create just the navbar.tmpl.partial here and the other partials will come from the default template/theme. Once you get the idea, customizing the site generated is actually really easy.

**Comment by vicancy** [comment]
Thanks @wekempf for the detailed explanation. 

You can use `docfx template export default` to export the `default` template, and pick the partials you want to override.

And please note that we don’t guarantee compatibility if you only overwrite part of the template, you may need to do some integration test when upgrading `docfx`.

**Comment by zulkarnainis** [comment]
Thanks @wekempf, i followed your instruction, and now i can replace default logo to my own logo, and i learn much from your project too, i really appreciate it. Thank you so much.

Thanks  too @viicancy for your information, i try template export default and i thinks i can get many information from the template.

Thanks all.

**Comment by daviwil** [comment]
@wekempf I also learned a lot from your doc project, nice work!

**Comment by travelerr** [comment]
Very helpful! Thank you
