### ISSUE TITLE
Is Microsoft documentation docfx now CommonMark compliant?

### ISSUE THREAD

**Issue by ghost** [dotnet/docfx#2648]
I am coming from this way:

https://github.com/jgm/pandoc/issues/4557 => https://github.com/dotnet/cli/pull/9081 => https://github.com/dotnet/docs

So CLI has a handwritten python script https://github.com/dotnet/cli/blob/20cd0f04b28c009838274b4ea741dfa132b07802/Documentation/manpages/tool/man-pandoc-filter.py, to remove docfx extensions from dotnet-cli tools docs, which is used during the pandoc processing / conversion to manpage.

I have been asked to encourage you guys to embrace CommonMark and treat the rest of additions as extensions to the original thing: https://github.com/jgm/pandoc/issues/4557#issuecomment-382099471. Is it already the case? :)

**Comment by vicancy** [comment]
We do support CommonMark, but not set as the default markdown engine. `docfx.config` to set `markdownEngineName` as `markdig` to enable CommonMark syntax:
```json
{
  "build": {
    "markdownEngineName": "markdig",
...
```

**Comment by herohua** [comment]
@kasper3 Have you tried the solution above to enable CommonMark in DocFX markdown engine?

**Comment by kasper3** [comment]
@herohua, I proposed https://github.com/dotnet/docs/pull/4963, but it was pushed to later this year.
Tools like pandoc to convert one text format to another, which is markdown to Unix manpages in case of dotnet/cli, will have to then wait later this year.

**Comment by xoofx** [comment]
@kasper3 docfx is switching to markdig which is CommonMark compliant and is going to be default soon (if it is not already the case). There is really no value of using Pandoc for converting markdown to HTML in docfx case (not C# based, impossible to develop specific C# extensions, Pandoc is not CommonMark compliant, does not support and won't likely never support DFM.. .etc.).

**Comment by kasper3** [comment]
>  Pandoc is not CommonMark compliant

@xoofx, if you follow this thread closely, this issue is way tangential to what you have commented :)

Pandoc actually is CommonMark complaint. Pandoc maintainer has sent me here (first comment) to request docfx to be CommonMark complaint. I was then introduced to markdig (thanks a lot btw!) engine. My interest in this engine is to see dotnet/docs repo start using markdig and all existing `.md` files in that repo are converted to CommonMark: https://github.com/dotnet/docs/pull/4963.

Why?

dotnet/cli uses pandoc to convert `dotnet/docs/tools/sdk` markdown documents  to manpage `.1` files (not HTML), when .NET Core package for Unix-like OSes are produced. See https://github.com/dotnet/cli/tree/80d542b8f4eff847a0f72dc8f2c2a29851272778/Documentation/manpages/tool

For that, we extend pandoc via python extension to convert docfx-style `.md` files to manpages `.1`, which is bit hacky https://github.com/dotnet/cli/blob/80d542b8f4eff847a0f72dc8f2c2a29851272778/Documentation/manpages/tool/man-pandoc-filter.py. When we requested pandoc guys to support docfx style markdown they replied: https://github.com/jgm/pandoc/issues/4557.

**Comment by xoofx** [comment]
As per issue jgm/pandoc#4557 and as also stated on some other forums, I still stand that Pandoc is not entirely CommonMark compliant:

> try to encourage DocFX to move to http://commonmark.org, which pandoc is slowly trying to do as well.

The work on the merge to markdig started one year ago by docfx teams but latest docfx release should have switched by default to markdig already. For the documentation of docfx to switch to CommonMark, can't comment much on that, and if that's the whole point of this issue, my apologize for hijacking the discussion! 😅 

Concerning the markdown to man pages, it should likely be just a couple of days of work to get the same functionality with markdig (and by extension a large part of it would be done also for DFM). Now that docfx is using markdig and have a full syntax tree of the markdown document, we can do pretty much any transformation with the documentation.

**Comment by kasper3** [comment]
Oh sorry, my bad. Pandoc is "slowly adapting" CommonMark. 😄

**Comment by superyyrrzz** [comment]
> The work on the merge to markdig started one year ago by docfx teams but latest docfx release should have switched by default to markdig already.

@xoofx One minor correction: DocFX's default engine is still DFM, while DocFX's homepage is generated [using Markdig](https://github.com/dotnet/docfx/blob/dev/Documentation/docfx.json#L65).

**Comment by xoofx** [comment]
> @xoofx One minor correction: DocFX's default engine is still DFM, while DocFX's homepage is generated using Markdig.

Hm, but when I downloaded the latest release and did a `docfx init` I got the markdig engine in the json, so it is not the same thing than `DocFX's default engine`?

**Comment by superyyrrzz** [comment]
I meant the markdown engine used is `dfm` if no config is given. Of course, you are right as most users will use `docfx init`'s default config with markdig engine. I just realized it has changed to markdig 😃

**Comment by superyyrrzz** [comment]
@xoofx Sorry for delay response... Yes, it has a standalone tool for this: https://www.nuget.org/packages/MarkdownMigrateTool/2.40.11

Sample usage:
```
MarkdownMigrateTool.exe -p {input globs} -o {output folder} -c {input root folder}
```

This tool should be enough for most community users. Actually we have an internal  tool, but it has much  more extra features that specific to internal writers. We can open it to public if they are indeed required.

/cc @qinezh @daxianji007 @yishengjin1413
