### ISSUE TITLE
Filter constructors from a class?

### ISSUE THREAD

**Issue by evilripper** [dotnet/docfx#2788]
I need to hide a constructors in a specified class, how I can filter it?

![capture2](https://user-images.githubusercontent.com/1646220/40268503-c5f30902-5b6e-11e8-9d30-14c151f9200e.PNG)
I read this
https://dotnet.github.io/docfx/tutorial/howto_filter_out_unwanted_apis_attributes.html
and I tried to hide a method, the constructors?

**Comment by superyyrrzz** [comment]
You can add `EditorBrowsableState.Never` to your constructor, like: https://github.com/dotnet/docfx/blob/54c8a750ee6a49bd99f315438ce8ad580501b101/src/Microsoft.DocAsCode.Plugins/EnvironmentContext.cs#L20

**Comment by evilripper** [comment]
`
        [EditorBrowsable(EditorBrowsableState.Never)]
        public PublicApiV1Controller(UserManager<ApplicationUser> userManager, 
                                     SignInManager<ApplicationUser> signInManager, 
                                     RoleManager<IdentityRole<int>> roleManager, `

I tried but the constructor continues to appear.

**Comment by superyyrrzz** [comment]
@TianqiZhang Can you help investigate this?

**Comment by superyyrrzz** [comment]
@evilripper I can't reproduce it. I try adding `[EditorBrowsable(EditorBrowsableState.Never)] ` to the test repo, and the filter can work: https://github.com/docascode/docfx-seed/blob/master/src/SampleClass1/CatLibrary/Class1.cs#L122

I'm not sure whether you missed the `using System.ComponentModel;` If it still can't work for you, could you help provide more detailed reproduce steps?

**Comment by dlplenin** [comment]
**Operation System:** Windows 10

**DocFX Version Used:**
![image](https://user-images.githubusercontent.com/2582026/89088234-e293a400-d35c-11ea-9097-4d2cefaa613d.png)

**Template used**: Default

**Steps to Reproduce:**

1.  Decorate with `[EditorBrowsable(EditorBrowsableState.Never)]`
![image](https://user-images.githubusercontent.com/2582026/89087988-ce02dc00-d35b-11ea-9c9d-b4939d4cac4a.png)
![image](https://user-images.githubusercontent.com/2582026/89088019-ed016e00-d35b-11ea-9c9c-c3d2c317931a.png)

2. `λ  docfx metadata` -> it works (filter ctor)

3.  Then add new documentation 
`EditorBrowsable` is used in Mail.cs and I have new documentation in EmailBody.cs
![image](https://user-images.githubusercontent.com/2582026/89088462-11f6e080-d35e-11ea-8e78-9b8a39ec3a00.png)

4. `λ  docfx metadata` -> stop working "Warning:[MetadataCommand.ExtractMetadata]No metadata is generated ..."

**Expected Behavior:**
Exclude ctor (only where code is decorated with `EditorBrowsable`) and & generate documentation.

**Actual Behavior:**
Remove ctor from documentation 😀, but the following changes dont generate metadata anymore 😢.
![image](https://user-images.githubusercontent.com/2582026/89088181-9cd6db80-d35c-11ea-9b81-6a0874c3e8c7.png)




PD: I used this:
`      ctorArguments: 
      - System.ComponentModel.EditorBrowsableState.Never`
but the same behavior.
