### ISSUE TITLE
Unable to run docfx on macOS: Unable to find msbuild.dll

### ISSUE THREAD

**Issue by esg-jayallan** [dotnet/docfx#2879]
**DocFX Version Used**: 
2.36.1.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. On macOS High Sierra 10.13.4 install docfx using Homebrew: `brew install docfx`
2. Clone docfx seed project: `git clone https://github.com/docascode/docfx-seed`
3. Run `docfx docfx.json --serve` in docfx-seed

**Expected Behavior**:
The build succeeds and the seed project example documentation is served on `http://localhost:8080` 

**Actual Behavior**:
The build fails with the following exception:
```
[18-06-12 06:39:26.484]Error:[MetadataCommand.ExtractMetadata]Unable to find msbuild from /usr/local/Cellar/mono/5.4.1.6/lib/mono/msbuild/15.0/bin/MSBuild.dll, please try downloading latest mono to solve the issue.
[18-06-12 06:39:26.490]Info:[MetadataCommand]Completed Scope:MetadataCommand in 33.3009 milliseconds.
[18-06-12 06:39:26.490]Error:Unable to find msbuild from /usr/local/Cellar/mono/5.4.1.6/lib/mono/msbuild/15.0/bin/MSBuild.dll, please try downloading latest mono to solve the issue.
[18-06-12 06:39:26.490]Info:Completed in 36.2465 milliseconds

Build failed.
```

The latest Mono package available on Homebrew is already installed:
```
$> brew upgrade mono
Error: mono 5.4.1.6 already installed
```

Homebrew does not offer a separate `msbuild` package, the available package `mono` declared as a dependency for `docfx` is not officially maintained by Microsoft: https://github.com/Microsoft/msbuild/issues/1685

docfx should utilize `msbuild` from the official Mono package (https://www.mono-project.com/) which is accessible via `/Library/Frameworks/Mono.framework/Versions/Current/Command/msbuild`. 

This issue does also occur when downloading the latest docfx.zip release directly instead of using Homebrew for installation.

**Comment by zeddee** [comment]
i got the same issue on 10.13.5.
managed to resolve it by installing mono from http://www.mono-project.com/ instead of using the one on brew.
it _is_ a bit misleading, however, to have the docfx brew package depend on the mono package on brew, because while the brew version and the mono-project.com versions are the same, brew's package seems to leave out certain libraries (msbuild apparently being one of them).

**Comment by esg-jayallan** [comment]
Thanks @zeddee 

I had Mono installed from Mono Project but an older version from a few months before (5.4.1.6 (tarball Mon Dec 11 14:59:42 GMT 2017)).

Upgrading to Mono 5.10.1.47 (Visual Studio channel) from Mono Project resolved the issue.

**Comment by superyyrrzz** [comment]
Do not use brew to install mono on macOS. Added to document: https://github.com/dotnet/docfx/commit/9bb81bec8b1be155a49723f1931e29f578f2e440#diff-fdb758ff857402e5bdc8a5e603900c53R49

**Comment by sethreidnz** [comment]
I know this issue is closed but I'm running into this issue on latest Macbook Pro with Apple M1 Max if that is relevant. I have installed mono and can execute it from my terminal. But when I try to install docfx using brew I get the following:

```
Error: mono: no bottle available!
You can try to install from source with:
  brew install --build-from-source mono
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

Any ideas how I can recover and get it working? I also tried to use the exe but can't seem to get that working on the mac either.
