### ISSUE TITLE
Anchor click behavior weird

### ISSUE THREAD

**Issue by robertmuehsig** [dotnet/docfx#3133]
**DocFX Version Used**: 2.37.2

**Template used**: default

**Steps to Reproduce**:

1. Go to https://dotnet.github.io/docfx/spec/metadata_format_spec.html (or any site)
2. Click a link from the "IN THIS ARTICLE" box
3. Browser should now jump to the corresponding header
4. Now click the on the link when you hover over the header 
5. Browser scrolls down.

**Expected Behavior**:

No scrolling.

**Actual Behavior**:

Weird scrolling effect.

![gif](https://user-images.githubusercontent.com/756703/43441027-a5a1e6be-9499-11e8-8856-57efb51fc61b.gif)

Browser: Version 67.0.3396.99 (Official Build) (64-bit)

I'm not 100%, but maybe this is linked to this issue https://github.com/dotnet/docfx/issues/2508

**Comment by superyyrrzz** [comment]
Seems like a bug... There is a logic to prevent the title from hidden by the header. Seems it now only works when hash changes:
https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.js#L1131

but failed to work when hash changes:
https://github.com/dotnet/docfx/blob/dev/src/docfx.website.themes/default/styles/docfx.js#L1133

Need more investigation to find out the root cause.
