### ISSUE TITLE
azure-docs-pr issue: document_version_independent_id, document_id error

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3150]

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/All/_git/Docs.DocFX.Impact/pullrequest/2258?_a=files&path=%2Fsource%2Fazure-docs-pr.docfx.yml

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/All/_git/Docs.DocFX.Impact/pullrequest/2290?path=%2F&_a=files

**Comment by 928PJY** [comment]
there are still some diff

**Comment by OsmondJiang** [comment]
they are expected for SDP files, we always use source path to calculate the document id, @live1206  and @herohua do you agree?

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2745?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Factive-directory%2Fsaas-apps%2Fworkfront-tutorial.mta.json&_a=files

**Comment by OsmondJiang** [comment]
all are different under: https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2745?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Factive-directory%2Fsaas-apps&_a=files

**Comment by OsmondJiang** [comment]
the root cause for above two case is: a -> b -> c scenario is not considered in v3 logic

**Comment by yufeih** [comment]
`documentId` is used by a lot of other services including GitHub based commenting. I suspect we might need to keep it as is including bugs caused by previous versions. I have two options in mind:

1. implement the buggy old behavior (not pretty)
2. add a config entry that let us selectively override `documentId` for particular documents

**Comment by OsmondJiang** [comment]
there are still some difference caused by unknown reason:

https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2816?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fcosmos-db%2Fquery-cheat-sheet.mta.json

https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2816?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fcosmos-db%2Flocal-emulator-export-ssl-certificates.mta.json

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2816?_a=files&path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fsearch%2Fsearch-api-preview.mta.json

**Comment by OsmondJiang** [comment]
the root cause  for above is that the A -> B but B is an absolute path with host name like "https://docs.microsoft.com". Since we are not decided how to do the redirection(rename +redirection), we are going to remove the host name("https://docs.microsoft.com") from redirection configuration during import

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/2850?_a=files
