### ISSUE TITLE
Params parameter with tuple type

### ISSUE THREAD

**Issue by matkoch** [dotnet/docfx#3211]
Method declarations like this:

```
public static string XmlPeekSingle(string path, string xpath, params (string prefix, string uri)[] namespaces)
```

cause docfx.console.exe to throw NullReferenceException here:

https://github.com/dotnet/docfx/blob/275e0c337ed9ea9145c54d49612c34950e687337/src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/NameVisitor.cs#L128

Symbol is of type `UnsupportedMetadataTypeSymbol`, namespace is null.

**Comment by matkoch** [comment]
Might be that this is a Roslyn bug?

**Comment by matkoch** [comment]
@herohua  Please reopen and mark as bug.

**Comment by superyyrrzz** [comment]
I thought @werwolfby had fixed this. I just tested it on 2.37.1 and it can work:
![image](https://user-images.githubusercontent.com/3831744/54282903-ee4fc080-45d7-11e9-8fda-47334d2e9b3f.png)

I also tried to put it in a class with no namespace. It will log warning saying no metadata generated, instead of error. Could you reproduce the error now? @matkoch

**Comment by matkoch** [comment]
I don't remember exactly, just got the notice of the issue being closed. However, the image doesn't look right exactly? `params[] namespaces` and `System.[]` is not really what I would expect.

**Comment by superyyrrzz** [comment]
Just notice this... This is indeed a bug.

**Comment by matkoch** [comment]
Thank you!

**Comment by werwolfby** [comment]
I was sure that everythimg were fixed, I’ll recheck it next week.

**Comment by yufeih** [comment]
This is fixed in the latest version:

![image](https://user-images.githubusercontent.com/511355/215404934-f395f5a4-df9f-4b72-9c06-4c22348a826e.png)

**Comment by werwolfby** [comment]
Hmm...
