### ISSUE TITLE
azure-docs-pr issue: git commit error

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3218]
articles/media-services/previous/media-services-mes-preset-H264-Multiple-Bitrate-16x9-SD.md

![image](https://user-images.githubusercontent.com/17958546/44215356-e4322480-a1a4-11e8-98b4-2e195cda6db3.png)

**Comment by yufeih** [comment]
The root cause we [cache](https://github.com/dotnet/docfx/blob/v3/src/docfx/lib/git/GitUtility.Native.cs#L235) git trees when loading git commits, but the trees are cached with [absolute names](https://github.com/dotnet/docfx/blob/v3/src/docfx/lib/git/GitUtility.Native.cs#L227) in case of folder rename.
