### ISSUE TITLE
Generated site behaves different in IE and chrome for non-English content (original: docfx生成网站在IE与谷歌中有不同的行为)

### ISSUE THREAD

**Issue by XzMitsui** [dotnet/docfx#3267]
**DocFX Version Used**: 2.38

**Template used**: (`default` or `statictoc` or contain custom template) 自定义默认

**Steps to Reproduce**:

1. 添加markdown文件
2. 使用docfx集成生成网站
3. 分别在IE和谷歌浏览器中运行

**Expected Behavior**:应该都是一个一致的、正常的、会渲染我设置的样式的网站

**Actual Behavior**:第一个问题是，之前我提出锚点异常，定位不准确的问题，但是我发现docfx官方API中调试界面也会报那个错误，但是它仍能定位到锚点的标题处，所以当我后来把本地md文件中的标题从中文改为英文后锚点就变得精确了。不过在IE浏览器中，即使它是中文的标题，它也是精确的。
第二个问题，就是关于页面等比例缩放。同样的，在IE浏览器中，我使用`Ctrl`+鼠标滑轮进行缩放，页面是等比例的，但是在谷歌中，侧边栏目录以及主体的内容都被挤飞，包括我做的一个绝对定位的下拉框在谷歌中都会跑偏。基于不同浏览器、不同内核会出现差异，考虑到其他用户使用浏览器的喜好，这个能够兼容吗。

---------- *Below is the summary of the issue for non-Chinese speakers* ----------
**Issue1**: Anchor position not accurate for Chinese title. IE works well, while Chrome doesn't work.
**Issue2**: Page zoom (`Ctrl` + `mouse scroll`) behaves differently in Chrome and IE.

**Comment by lextm** [comment]
@XzMitsui Even though many Microsoft engineers on docfx understand Chinese, it is more common to discuss issues in such repositories in English (almost all 900 issues), so that all readers can understand what has been discussed. That's why the issue template is in English when you propose a new issue.

**Comment by superyyrrzz** [comment]
Of course, it's recommended to discuss in English here. The benefit is obvious:
1. More audience can understand the issue, so that they can join discussion and share their thoughts. Your issue will be more likely to be resolved.
2. More audience can learn from it if they meet the same issue.

@XzMitsui must feel more comfortable to discuss in Chinese. I think it's OK as long as we can understand. I have also translated #3110 to benefit more audience (2). 

However, I'd still highly recommend to discuss in English to enable more people to join discussion (1). You don't need to speek like native speeker for others to understand you. At least I can understand your English comment above 😄

**Comment by XzMitsui** [comment]
@superyyrrzz Ok ok,in English.So what is the solution to this issues please?:）

**Comment by superyyrrzz** [comment]
@XzMitsui Need some investigation on this. We still have no tests for non-English content.

**Comment by XzMitsui** [comment]
@superyyrrzz OK,If there is a solution please let me know about.Thanks a lot.

**Comment by herohua** [comment]
@XzMitsui is it possible you share the link of your published pages for us to investigate?

**Comment by XzMitsui** [comment]
@herohua Not at the moment. Documents I make in the company and publish them on the company's servers are private segments that are not accessible externally. In the national day, I will send a video to you.
