### ISSUE TITLE
azure-docs-pr: UID identification error

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3365]
https://ceapex.visualstudio.com/Engineering/_git/Docs.DocFX.Impact/pullrequest/3081?path=%2Fsource%2Fazure-docs-pr.output%2Fazure%2Fvirtual-machines%2Flinux%2Ffaq.page.html&_a=files

![image](https://user-images.githubusercontent.com/19990166/45007603-2080d400-b031-11e8-9e60-a3309e9829ee.png)

**Comment by OsmondJiang** [comment]
@yufeih

**Comment by yufeih** [comment]
This is a [source](https://raw.githubusercontent.com/MicrosoftDocs/azure-docs-pr/markdig-migration-v3/articles/virtual-machines/windows/faq.md?token=AAfNe7cnCro7TaeGYfgyRz72mn5Aw7I4ks5blz5qwA%3D%3D) issue, it has been fixed in [live](https://raw.githubusercontent.com/MicrosoftDocs/azure-docs-pr/live/articles/virtual-machines/windows/faq.md?token=AAfNe52LAdsI9A9rYZeaFOEhId-GosJyks5blz5owA%3D%3D)
