### ISSUE TITLE
azure-docs-pr: Relative path doesn't match 

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3392]
[functions-cli-create-function-app-github-continuous.md](https://raw.githubusercontent.com/MicrosoftDocs/azure-docs-pr/markdig-migration-v3/articles/azure-functions/scripts/functions-cli-create-function-app-github-continuous.md?token=AoPpFLr5FD0AxJoNpwZhSgk0e1Xz9ZH5ks5bn3uhwA%3D%3D)  
search 'cli-script-clean-up'
![image](https://user-images.githubusercontent.com/42199316/45277635-a1414380-b4fb-11e8-9604-137e9a1e3d57.png)

**Comment by yufeih** [comment]
This should be a markdig `[!INCLUDE]` extension problem @yishengjin1413 . We should recognize it as an include.

Right it is treated as a link, and v3 correctly resolves that link to an URL. The missing `../` in red is because the _include_ folder has been redirected to _azure/_ in our _routing_ config.

**Comment by mingwli** [comment]
![image](https://user-images.githubusercontent.com/42199316/45291157-f09b6a00-b523-11e8-9ce0-1389015e5c72.png)  
This `space`.

**Comment by 928PJY** [comment]
the content issue will bring same error to v2 and v3, but the result should same, it seems href of v3 is not correct

**Comment by 928PJY** [comment]
because of the output of `includes/` folder is `azure/includes/`, so the v3 resolve result is correct, there should be a bug in v2

**Comment by herohua** [comment]
@herohua to follow up with @928PJY
