### ISSUE TITLE
azure-docs-pr: duplicate redirection issue

### ISSUE THREAD

**Issue by mingwli** [dotnet/docfx#3413]
>articles/virtual-machines/windows/classic/web-app-visual-studio.md: /azure/app-service/
>articles/virtual-machines/linux/classic/web-app-visual-studio.md: /azure/app-service/

`/azure/app-service/` is defined twice, once in redirection, once in `redirectionsWithoutId`.

v2 doesn't follow redirection, but v3 followed redirection. 
![image](https://user-images.githubusercontent.com/42199316/45416678-09865580-b6b3-11e8-9e2b-1a0ab8273d62.png)

**Comment by 928PJY** [comment]
there is two redirection rule with the same redirect_url:
![image](https://user-images.githubusercontent.com/17958546/45466771-76026280-b74e-11e8-8c90-79879721a13f.png)
![image](https://user-images.githubusercontent.com/17958546/45466773-7b5fad00-b74e-11e8-98df-46f8b624e11a.png)
but the first one is with_document_id and the second is without_document_id, so the expected behavior is taking the first redirection file document id, which is the behavior of v3.
since the redirect_url is site path of an `index.yml`, which go through the yaml processor in v2, it will use itself's source path to generate document_id since it doesn't have the redirection file info.
so it is a bug of v2, we should check-in this diff
