### ISSUE TITLE
improve publishing performance

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#4033]

**Comment by OsmondJiang** [comment]
#4075

**Comment by yufeih** [comment]
We could remove worker warm up for v3

**Comment by yufeih** [comment]
The current PR checkout workflow does not utilize an existing `refs/pulls/xxx` branch, it instead does a local checkout and merge, because PR validation rely on the last known target branch build result for strict report comparison.

If we could afford unstrict comparison, checkout to `refs/pulls/xxx` may save us 70s. (docfx build itself runs within 80s).
