### ISSUE TITLE
License issues with DocFX packages (AGPL packages are not compatible with MIT)

### ISSUE THREAD

**Issue by JeremyHenderson** [dotnet/docfx#4250]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Any

**DocFX Version Used**: 
2.39.2.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:
1. Run [Black Duck](https://www.blackducksoftware.com/) on DocFX 
2. Open the report. Notice AGPL packages in the DocFX package

**Expected Behavior**:
DocFX is licensed under MIT, but contains code that is incompatible with that license. Fix/replace software packages that are using the incompatible license or clarify how those packages can be used under DocFX MIT license.

**Actual Behavior**:
The following packages come back from the scan as GNU AGPL 3.0. This puts the software I am developing at risk.

- iTextSharp v 5.5.11 GNU Affero General Public License v3.0
- iTextSharp v 5.5.8 GNU Affero General Public License v3.0
- Json.NET Schema v 3.0.5 GNU Affero General Public License v3.0
- Json.NET Schema v 2.0.10 GNU Affero General Public License v3.0

**Comment by superyyrrzz** [comment]
@JeremyHenderson Thank you for reporting this! I am seeking help from legal expert to fix this.

**Comment by KalleOlaviNiemitalo** [comment]
It seems DocFX v2 first builds each PDF by running wkhtmltopdf (LGPLv3) and Qt (LGPLv2.1 or GPLv3) as an external process but then uses `iTextSharp.text.pdf.PdfReader` and `iTextSharp.text.pdf.PdfStamper` to add "outlines" that let PDF readers show the TOC hierarchy. If the iTextSharp references were removed from DocFX, perhaps it would be possible to make wkhtmltopdf add the outline instead. The `wkhtmltopdf --outline` option is even on by default, but perhaps the input HTML is not in a suitable format for libwkhtmltox to figure out the correct outline; [src/lib/outline.cc](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/4f1b79df10d91ec2cbd286c7b24b7604df30a8a4/src/lib/outline.cc) seems to be searching for HTML `h1` - `h9` elements, so it might not understand the relations between HTML files.

**Comment by KalleOlaviNiemitalo** [comment]
`Newtonsoft.Json.Schema` is referenced in `src/Microsoft.DocAsCode.Build.SchemaDriven/` and `tools/YamlSplitter/`.  However, I'm not sure `Microsoft.DocAsCode.Build.SchemaDriven` actually does anything with it if DocFX is run without a custom template that defines a JSON schema.  The DocFX v2 source tree contains these JSON schemas:

- `Documentation/custom_template/schemas/Dashboard.schema.json`: An example.
- `schemas/v1.0/schema.json`: a meta-schema, would be used for validating schemas, but if `.GetResourceStreams(@"^schemas/.*\.schema\.json")` in `DocumentBuilder.LoadSchemaDrivenDocumentProcessors` does not find any JSON schemas from templates, then it never calls `DocumentSchema.Load`, which would use this.
- `test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/**`: Many schemas, but these are for tests.

So, it might be feasible to rip these out without hurting normal use.  As a first step, perhaps `Microsoft.DocAsCode.Build.SchemaDriven` can be made optional so that it and `Newtonsoft.Json.Schema.dll` can be deleted from the installation directory without ill effects; such a change would help users ensure that DocFX uses no AGPL code at run time.  Users that have custom JSON schemas would have to keep those DLLs and either purchase a commercial license from Newtonsoft or cope with the AGPL requirements.

Microsoft had [announced](https://github.com/dotnet/announcements/issues/90) that they are developing a new JSON library for .NET Core, but that doesn't seem to include JSON Schema validation.

**Comment by superyyrrzz** [comment]
@KalleOlaviNiemitalo Thank you for your detailed suggestion! I have not looked into the code, but your information is very useful. Generally, if possible, I'd like to find a way to resolve this without too much code change due to resource limitation.

We use JSON schema validation a lot internally as we have a lot of schemas for docs.microsoft.com, with a purchased license. So this could be remove but will need some change to make it work internally.

**Comment by KalleOlaviNiemitalo** [comment]
You might ask your legal expert about:
- Whether some legal notices need to be added to the release zip files.
- Who is at risk of triggering the "if you modify the Program" condition in section 13 of AGPLv3.
- Whether Microsoft's purchase of GitHub is relevant to clause 6. d) of AGPLv3.

Is Microsoft internally using the same DocFX binaries you publish at GitHub, or are they built with different options?  Perhaps it could be made to work so that Microsoft.DocAsCode.Build.Engine loads Microsoft.DocAsCode.Build.SchemaDriven only if `--schemaLicense` is specified (with `--schemaLicense AGPL` handled as a special case). I believe the coupling between Microsoft.DocAsCode.Build.Engine and Microsoft.DocAsCode.Build.SchemaDriven is looser than that between Microsoft.DocAsCode.Build.SchemaDriven and Newtonsoft.Json.Schema, so the code would be easier to cut off at that boundary.

For users though, it seems clearest if DocFX can be both built and used with no GPL or AGPL components, even if the license terms of such components would allow the use.

The Newtonsoft.Json (not .Schema) assemblies also define some types for JSON schemas. Those types are deprecated but is it possible they could work well enough for DocFX anyway?

I wish NuGet made these things easier somehow.

**Comment by icnocop** [comment]
FWIW, [PDFSharp](https://github.com/empira/PDFsharp) and [PDFSharpCore](https://github.com/ststeiger/PdfSharpCore) have an MIT license.

**Comment by icnocop** [comment]
@KalleOlaviNiemitalo , FYI, I added the ability to specify the type of outline to use in `docfx.json` when generating a PDF in commit https://github.com/dotnet/docfx/pull/4289/commits/36d50cc7aa23bdfbb1b2dfccfbe1eaecdf97a56c.

The only difference I noticed with `WkDefaultOutline` and `DefaultOutline` is that outlines with children are not expanded by default when using `WkDefaultOutline`.

**Comment by icnocop** [comment]
I went ahead and replaced iTextSharp with [PDFSharp](https://github.com/empira/PDFsharp) in https://github.com/dotnet/docfx/pull/4289/commits/4d98f6692fb7d3d58615348c6c12bd9f1b5d3b34 which is part of PR #4289.

**Comment by icnocop** [comment]
I found a couple of possible alternatives to Newtonsoft.Json.Schema:
https://github.com/microsoft/jschema
https://github.com/RicoSuter/NJsonSchema

**Comment by KalleOlaviNiemitalo** [comment]
I was worried about how `Microsoft.DocAsCode.Build.SchemaDriven` applies the [nonstandard properties](https://dotnet.github.io/docfx/spec/docfx_document_schema.html#property-object) from the DocFX document JSON schema to the JSON document; does it expect the JSON schema validator to annotate the document with schema information? However, it looks like `DocumentSchema.LoadSchema<T>` recursively builds DocFX's own representation of the schema, and that is what DocFX uses for processing the properties of JSON objects; it is not tied to validation. That makes DocFX easier to port to a different JSON schema implementation.

**Comment by KalleOlaviNiemitalo** [comment]
> I found a few possible alternatives to Newtonsoft.Json.Schema:
> https://github.com/microsoft/jschema (https://www.nuget.org/packages/Microsoft.Json.Schema.Validation/)

The `Microsoft.Json.Schema.JsonSchema` class doesn't seem to support nonstandard properties in schema objects. I imagine that wouldn't be hard to add, though. It also has [`[JsonProperty("$$ref")]`](https://github.com/Microsoft/jschema/blob/7358e25f534e29130240b60a10b4cc7d945cc5dc/src/Json.Schema/JsonSchema.cs#L381) with a double dollar sign, which looks like a bug.

(Supporting only JSON Schema Draft 4 rather than Draft 7 does not seem to be a problem, as DocFX itself is using `"id"` rather than `"$id"`.)

> https://github.com/RicoSuter/NJsonSchema (https://www.nuget.org/packages/NJsonSchema/)

`NJsonSchema.JsonSchema4` doesn't seem to support nonstandard properties, either.

> https://github.com/gregsdennis/Manatee.Json (https://www.nuget.org/packages/Manatee.Json/)

That implements [`Manatee.Json.Schema.JsonSchema.OtherData`](https://github.com/gregsdennis/Manatee.Json/blob/cd392caa22fdc11cf522f5ea7a09999bf70ba42d/Manatee.Json/Schema/JsonSchema.cs#L51), which should work for DocFX. And it is using DocFX for [its own documentation](https://gregsdennis.github.io/Manatee.Json/). 😁

**Comment by superyyrrzz** [comment]
Hot discussion here 😄 Seems lots of questions here:

> Is Microsoft internally using the same DocFX binaries you publish at GitHub, or are they built with different options?

Same, but with much more plugins.

>  I believe the coupling between Microsoft.DocAsCode.Build.Engine and Microsoft.DocAsCode.Build.SchemaDriven is looser than that between Microsoft.DocAsCode.Build.SchemaDriven and Newtonsoft.Json.Schema, so the code would be easier to cut off at that boundary.

Good idea! It is easier to move this entire processor internally. However I am not sure if there is any community user using this. If so, It could be more friendly to only move the schema validation.

> For users though, it seems clearest if DocFX can be both built and used with no GPL or AGPL components, even if the license terms of such components would allow the use.

Sorry I am lack of knowledge about license issues. Do you mean it makes some difference for DocFX user, if DocFX uses only MIT packages, or DocFX uses some AGPL packages but with proper notice embedded (if feasible)?

**Comment by KalleOlaviNiemitalo** [comment]
> Do you mean it makes some difference for DocFX user, if DocFX uses only MIT packages, or DocFX uses some AGPL packages but with proper notice embedded (if feasible)?

AGPL seems to be [banned at Google](https://opensource.google.com/docs/using/agpl-policy/). I wouldn't be surprised if other companies had similar policies.

**Comment by JeremyHenderson** [comment]
I've been lurking and following the progress on this thread (Thank you for everything so far!)

> AGPL seems to be banned at Google. I wouldn't be surprised if other companies had similar policies.

That is the case with AGPL in the company I work for. Which is why we are currently increasing the depths of our scans into the software we are using. We want to have confidence that we are license compliant and AGPL free.

**Comment by KalleOlaviNiemitalo** [comment]
> Good idea! It is easier to move this entire processor internally. However I am not sure if there is any community user using this. If so, It could be more friendly to only move the schema validation.

I'm not using the schema-driven document processor but I'm maintaining some documentation for which it could be useful, if I could find the time to learn the template syntax. I would prefer that it remain available but the AGPL problem seems more urgent.

`DocumentSchema.LoadSchema<T>` nowadays examines the Newtonsoft.Json.Schema objects and builds DocFX's schema model from that information. If schema validation were removed, this would have to be changed to read the schema as JSON and examine that tree instead. I think the main difficulty there is `$ref`, as Newtonsoft.Json.Schema seems to resolve those on its own and DocFX would then have to do it.  For that reason, it could be easier to switch to Manatee.Json than remove validation from Microsoft.DocAsCode.Build.SchemaDriven.

**Comment by KalleOlaviNiemitalo** [comment]
> However I am not sure if there is any community user using this.

[Searching for the DocFX schema URL on GitHub](https://github.com/search?q=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocfx%2Fschemas%2Fv1.0%2Fschema.json&type=Code) finds many hits but all such schemas seem to be in Microsoft repositories or in forks of such or copied from DocFX.

Could removing Microsoft.DocAsCode.Build.SchemaDriven cause difficulty to community contributors who want to edit e.g. PowerShell module documentation and test building it locally before making a pull request?

**Comment by superyyrrzz** [comment]
@KalleOlaviNiemitalo Community contributors could use PR preview link to validate their change. Local build does not work now as it need access to some private repo.

Seems the effort will not be too large if DocFX switches to Manatee.Json. However, if the effort is large and no one from community is actually using it, we will consider removing schema processor.

**Comment by icnocop** [comment]
Unfortunately, I had to revert PDFSharp back to iTextSharp because of issue https://github.com/dotnet/docfx/issues/4407.

**Comment by superyyrrzz** [comment]
Thank you for all the discussions and ideas here. We have completed the internal legal review and get approved. Here are some comments:
> Microsoft has a separate site license for this, which allows cloud use and distribution of the unmodified binary form of the software with our own software, which may not be a competing product with Newtonsoft Software. No attribution is required.

**Comment by hpaul-osi** [comment]
@superyyrrzz, I was hoping to clarify a few points regarding this item.  Your last comment indicates that your legal team approved the use of Json.NET Schema as compatible with the MIT license used by DocFX.  However, this item remains open and iTextSharp was reintroduced with the resolution of #4407.

Is it accurate to say that the most recent version of DocFX (2.43.3) is not compatible with the MIT license due to the inclusion of iTextSharp?  If so, is the last version using PDFSharp compliant (2.42.1)?

**Comment by superyyrrzz** [comment]
@hpaul-osi Sorry for the unclear message. Actually, we have 2 internal reviews: one for Json.NET Schema, one for iTextSharp. Both got approved as compliant.

**Comment by KalleOlaviNiemitalo** [comment]
Even if Microsoft's distribution of DocFX from GitHub with these AGPL dependencies is legal, and the use at docs.microsoft.com is also legal, that does not help users at companies that have anti-AGPL policies.

**Comment by superyyrrzz** [comment]
@KalleOlaviNiemitalo I agree with your concern. We are improving this in v3 to ensure it APGL free. @yufeih While in v2, we may not take it as high priority to replace these APGL packages due to the above reason.

In many user cases, DocFX is used temporarily in CI to generate document site. It is not a package reference that will finally ship with user's products. Hope this can somehow mitigate this issue.

**Comment by KalleOlaviNiemitalo** [comment]
I am primarily concerned about whether having CI run DocFX with the AGPL components automatically after a user pushes to a repository, and post the results to a web site at which the same user can access them, could be construed as "users interacting with it remotely through a computer network" as in AGPLv3 section 13.

I suppose I should start trying DocFX v3 when I get time. Currently, I am more interested in using it for Markdown-only documentation than for .NET API references.

**Comment by KalleOlaviNiemitalo** [comment]
This issue is still valid.

**Comment by icnocop** [comment]
💡 Maybe we can look into replacing iTextSharp with [PdfPig](https://github.com/UglyToad/PdfPig).

PdfPig is a fairly new project, and is license under [Apache 2.0](https://github.com/UglyToad/PdfPig/blob/master/LICENSE).

I don't yet know which features docfx uses in iTextSharp which are missing in PdfPig, if any.

**Comment by herohua** [comment]
+ @easonyq

**Comment by KalleOlaviNiemitalo** [comment]
The previously suggested Manatee.Json library has been deprecated in the meantime.

**Comment by icnocop** [comment]
Another option: https://github.com/QuestPDF/QuestPDF

Also see https://github.com/quozd/awesome-dotnet#pdf

**Comment by yufeih** [comment]
Our latest thinking for PDF is to use CSS print media for PDF template and generate PDF using  [`Playwright`](https://playwright.dev/) to instruct headless chrome to create PDF per page, then stitch all the pages together.

**Comment by vicancy** [comment]
> Our latest thinking for PDF is to use CSS print media for PDF template and generate PDF using [`Playwright`](https://playwright.dev/) to instruct headless chrome to create PDF per page, then stitch all the pages together.

Just realized that it requires chrome to be installed on the running machine
