### ISSUE TITLE
restore does not gracefully handle force push

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4444]
If a dependent git repo is force pushed, `docfx restore` currently does not handle unknown commit gracefully.

**Comment by OsmondJiang** [comment]
@fenxu , what you think the behavior like for PR building with dependency lock?

**Comment by fenxu** [comment]
It's a corner case IMO. The error will happen only when
1. User do a force push
2. Before branch build finishing, user create a PR.

There's workaround, that's close and reopen the PR after target branch build finished.

I think we can fix that but not so high priority because usually partners doesn't allow user to do force push.

cc @yufeih @OsmondJiang

**Comment by fenxu** [comment]
About fix, I don't think we have ability to detect whether a force push is happened. So that we don't know whether we should respect the cache or not.

Maybe we can improve error message to let uesr close/reopen the PR after target branch finishing build.
