### ISSUE TITLE
[Question]: Host docfx site in subfolder in IIS

### ISSUE THREAD

**Issue by MarcusKohnert** [dotnet/docfx#4449]
**Operation System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
docfx 2.40.10.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:
I'd like to host the docfx static website next to an Angular WebApp.
Uri-Layout:
http://someUri/docs/* 👉 serve static docfx page
http://someUri/*          👉 serve Angular route

1. docfx build
2. host in IIS under <virtualDirectory path="/docs" ...
3. redirect every request to docs* via web.config
```xml
<rule name="rewriteToDocs" stopProcessing="true">
  <match url="^docs/(.*)$" />
  <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
  <action type="Rewrite" url="docs/{R:1}" />
</rule>
```

I can't come up with a working solution to host a docfx generated site under a subfolder. Is this possible? Does anyone have a hint?

I've tried to set the base of the website to "/docs" 👉 `<base href="/docs/">` [base tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)

I've also tried to set the {{_rel}} tag in globalMetadata.

But something is always broken, be it the top menu, the sidebar or the links between pages.

Thanks in advance for any ideas.

**Comment by KalleOlaviNiemitalo** [comment]
Is your problem that rewrite rules added for Angular are grabbing the requests and not letting them through to the virtual directory?

**Comment by MarcusKohnert** [comment]
The routing between Angular and docfx is working fine. So no, Angular is not grabbing requests. To be honest that's only a little side-note that Angular is hosted under root. I could be anything else.

The problem are the hrefs that are generated by docfx. I couldn't find a solution for example to specify that only absolute paths should be generated.
We usually use the following syntax to specify a link. [about](/manual/about.md)

Would a repro repo be useful? If so, would a web.config for IIS be okay?

**Comment by KalleOlaviNiemitalo** [comment]
> The problem are the hrefs that are generated by docfx. I couldn't find a solution for example to specify that only absolute paths should be generated.

Why would you want only absolute paths?

I have an intranet IIS site in which a few virtual directories contain only static files generated by DocFX v2.  Within each DocFX-generated directory, links between HTML files have relative URIs so that subfolder within the IIS site does not matter. This is the default behavior of DocFX; I didn't need to add any base tags or _rel metadata or rewrite rules to get that working. What is different in your use case?

> We usually use the following syntax to specify a link. `[about](/manual/about.md)`

I don't think such a link works even if you put the DocFX directory at the root of the site.  I tried the following with DocFX 2.41.0 now:

1. `docfx init`
2. Accept all defaults.
3. Add `docfx_project/articles/greeting.md` with content:
   ```Markdown
   # Greeting

   [Hello, world!](/articles/intro.md)
   ```
4. `docfx docfx_project/docfx.json --serve`
5. Open `http://localhost:8080/articles/greeting.html` in a browser.
6. View the HTML source:
   ```HTML
   <p><a href="/articles/intro.md">Hello, world!</a></p>
   ```
7. Click the "Hello, world!" link and get a blank page, because there is no `docfx_project/_site/articles/intro.md`.  There is `docfx_project/_site/articles/intro.html`, instead.

**Comment by MarcusKohnert** [comment]
Thanks for replying and giving me confidence that my desired scenario should work. 🙌

It works now even without the base tag.
It was an IIS misconfiguration.
The request to /docs failed.
The request to /docs/ worked.
So everything is fine now and the traffic will be routed to /docs/.

Thanks again for your effort.
