### ISSUE TITLE
metadata ROBOTS should be upper case

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#4466]
https://ceapex.visualstudio.com/Engineering/All/_git/OpenPublishing.Build?path=%2FLibraries%2FPageRenderer%2FUtility%2FMetadataUtility.cs&version=GBdevelop&line=159&lineStyle=plain&lineEnd=160&lineStartColumn=1&lineEndColumn=1

Needs to verify if output metadata ROBOTS should be upper case

**Comment by live1206** [comment]
https://moz.com/learn/seo/robots-meta-directives
it does not need to be upper case

**Comment by yufeih** [comment]
The original ToUpperCase was simply because SiteMapGenerator initially only supports upper case ROBOTS, now it supports both `ROBOTS` and `robots`: https://ceapex.visualstudio.com/Engineering/_git/OpenPublishing.DocumentHosting?path=%2FSource%2FSitemapsGenerator%2FSitemapsGeneratorService.cs&version=GBmaster&line=414&lineStyle=plain&lineEnd=415&lineStartColumn=1&lineEndColumn=1
