### ISSUE TITLE
Use unicode in TOC entries

### ISSUE THREAD

**Issue by josesimoes** [dotnet/docfx#4791]
**Operation System**: `Windows`

**DocFX Version Used**: 2.43.2.0

**Template used**: `default` 

**Steps to Reproduce**:

1. Use Unicode char in TOC entry (ex: `#[&#128295; Building](content/building/index.md)` )
2. The output is the code as a text.

![image](https://user-images.githubusercontent.com/1881520/60030730-69c31280-969b-11e9-967b-04d04ab60b6c.png)

**Expected Behavior**:
Would like that the output would show the Unicode representation and not the code as plain text.

Using Unicode in "regular content" like a title in an article does produce the expected output:
![image](https://user-images.githubusercontent.com/1881520/60030890-ae4eae00-969b-11e9-9951-1c42963405fc.png)

**Comment by josesimoes** [comment]
This keeps beinf of interest

**Comment by superyyrrzz** [comment]
Sorry for late reply. You can find an example [here](https://raw.githubusercontent.com/dotnet/docfx/dev/Documentation/tutorial/walkthrough/toc.md) that works without unicode.

The consideration behind is that docfx take all the string in TOC entry as plain text, so they will be HTML encoded before display on-page. This can ensure TOC like `# [List<T>](list.md)]` can work by default. Otherwise, `<T>` will disappear which be mistaken as an unrecognized HTML tag.

**Comment by josesimoes** [comment]
Understood! Thank you for the explanation, it makes sense.

Anyway to add to the parser a regex filter (or equivalent) that "peeks" the content to find if there are Unicodes in the content and changes the output accordingly?
