### ISSUE TITLE
Class Summary in Conceptual Markdown

### ISSUE THREAD

**Issue by weifenluo** [dotnet/docfx#4818]
I'm writing documentation using DocFX and would like to include class summary in my conceptual markdown files. I came across [this DocFX documentation][1] and have done the following:

1. I added a simple template file _summary.tmpl:
```
{{summary}}
```

2. In my conceptual markdown file:
```
<xref uid="MyClass" template="_summary.tmpl" /> 
```

This does not work as expected. The conceptual markdown is rendered as a link to the API class documentation page, not just the summary - it appears the template  is not applied.

What am I doing wrong?

[1]: https://dotnet.github.io/docfx/spec/docfx_document_schema.html#66-xrefproperties

**Comment by superyyrrzz** [comment]
2 changes to make it work:
1. `{{summary}}` => `{{{summary}}}`: otherwise all the HTML tags will be HTML encodes and show on page.
2. add `result["summary"] = item.Summary`  to https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.Build.ManagedReference/ManagedReferenceDocumentProcessor.cs#L251: The reason is that you are refering to schema driven processor's document, while the C# API uses managed referenced processor. Its `xrefProperties` are hard coded in my referenced code. You need to change code to add summary into it.

**Comment by weifenluo** [comment]
I did read all the documentation and cloned the repo during last 2 days trying to figure out the internals of DocFX. Finally I decide to give up by authoring conceptual markdown without referencing class summary. I realized I'm just a entry level beginner of DocFX, I'm expecting using DocFX as a black box tool, not to work at source code level...

Thanks any way for your reply.
