### ISSUE TITLE
[Question] Current status for the new version 3.0.

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/docfx#4874]
This is just a question, because unfortunately the project for version 3.0 was removed, and also the milestone. The linked [roadmap](https://github.com/dotnet/docfx/blob/v3/docs/roadmap.md) for version 3.0 is not up to date anymore. And so I just wanted to ask about the current state of things. Until when is version 3.0 planned? How many features are still missing? When should you upgrade documentation from the current version 2.0 to version 3.0? Are there any best practices? Pre-releases can already be installed. Do they make sense?

I would like some short answers here. Then we can close this issue very quickly!

Many thanks for the help in advance!

**Comment by yufeih** [comment]
Thank you for bringing up this concern. 

We've recently moved work item tracking from GitHub to azure devops for v3 because it gives us better tracking across features within Microsoft The projects and issues for v3 are gradually removed from GitHub, but we are still actively developing it on GitHub.

We've made good progress on v3 for https://docs.microsoft.com (our first party consumer). Several repos under [MicrosoftDocs](https://github.com/MicrosoftDocs) have been using v3 in production, and we are kicking off massive v3 migration for the rest.

On the community side, v3 still misses two critical parts: template and .NET api document extractor. The pre-release is production quality for _docs.microsoft.com_, but it might not make sense for the community at the moment due to lacking of template and .NET api doc.

**Comment by FSharpCSharp** [comment]
Thank you for your feedback! It's good to hear that things are definitely moving on. It was also on the old agenda (please correct me if I am wrong) that the automatic PDF generation and linking should be available by default in the template and during creation. An important point that was still on the old roadmap was localization.

Does it go on in these points, or have they been postponed? To my knowledge at least the PDF functionality was already part of docs.microsoft.com.

**Comment by yufeih** [comment]
I've [updated](https://github.com/dotnet/docfx/commit/39a1a780599ea71a1de171a0a3d3be7f36ee3649) roadmap to reflect a more recent status.

**Comment by FSharpCSharp** [comment]
Thank you very much. With that we can close this issue. All questions answered! Super, thank you very much for the quick and detailed reaction.
