### ISSUE TITLE
Improve this Doc link not appearing

### ISSUE THREAD

**Issue by MJ1823** [dotnet/docfx#4936]
We are using docfx on windows for our documentation website, I tried all the suggested method and still not able to the `Improve this doc` button. we are using GitLab as repository

Could you please help me ?

**Comment by KalleOlaviNiemitalo** [comment]
`"_gitUrlPattern": "github"` is said to work with GitLab as well, according to #942 and #1144. Are you using that?

If that does not work for some reason, you could also try these approaches in DocFX v2:

- Edit [src/docfx.website.themes/common/common.js](https://github.com/dotnet/docfx/blob/v2.41/src/docfx.website.themes/common/common.js), which recognizes git repository URLs of github.com and visualstudio.com, and generates the URLs for the "Improve this doc" links.

- Alternatively, add a custom template in which the [`exports.preTransform`](https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html#extension-for-preprocessor-file) function sets `model.docurl` based on the values of `model._gitUrlPattern`, `model._gitContribute`, and `model.documentation.remote`. Then, list both `"default"` and your custom template in docfx.json. Because the custom template sets `model.docurl`, the theme uses that value and does not call `getImproveTheDocHref`.

**Comment by KalleOlaviNiemitalo** [comment]
Also, the remote has to be named "origin". https://github.com/dotnet/docfx/blob/3cde049d78c60026badb4825fca055d5433069a5/src/Microsoft.DocAsCode.Common/Git/GitUtility.cs#L35-L36

**Comment by MJ1823** [comment]
I tried `"_gitUrlPattern": "github"` as mentioned the comments with no success

**Comment by superyyrrzz** [comment]
Could you provide your `docfx.json`, and the result of `git remote -v`?

**Comment by Konard** [comment]
For me these two settings worked:
```
      "_gitContribute": {
        "branch": "master"
      },
      "_gitUrlPattern": "github"
```
`"_gitUrlPattern": "github"` alone was not enough.
https://github.com/linksplatform/Threading/blob/a7a64f2adb2a8db16a5624a0a59d37d54e5b9791/docfx.json#L28
