### ISSUE TITLE
How to omit constructor arguments on attribute?

### ISSUE THREAD

**Issue by QFSW** [dotnet/docfx#5694]
**Operation System**: Windows

**DocFX Version Used**: 2.51.0.0

Some attributes end up with very unwieldy constructors
![image](https://user-images.githubusercontent.com/11485449/77846639-5a836f00-71af-11ea-9009-7e070164c252.png)

Is it possible to still include the attribute decoration but remove all of its arguments from the api reference?

**Comment by KalleOlaviNiemitalo** [comment]
That output makes me wonder if there is a bug where `Platform.AllPlatforms` already includes all the other bits but DocFX lists them regardless.

**Comment by QFSW** [comment]
If this helps you understand the issue any better
In my code I have a bitwise flags enum `Platform`, so each bit represents one platform
Hence `AllPlatforms` is defined as `~0` to cover all platforms

**Comment by KalleOlaviNiemitalo** [comment]
I think the bug is here: <https://github.com/dotnet/docfx/blob/ac8024bc50bd47d748ff99791a70e6f1ef6152d8/src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/Visitors/CSYamlModelGenerator.cs#L896-L909>

**Comment by KalleOlaviNiemitalo** [comment]
I mean, if `Platform.AllPlatforms == (Platforms)~0`, and the argument of the attribute constructor is `Platforms.AllPlatforms`, then DocFX should just emit that, rather than a huge bitwise OR expression. If that bug were fixed, then your HTML would get a much shorter syntax for the attribute, which could be good enough for you even though it would not satisfy your stated request.

DocFX could use the same algorithm as in `Enum.ToString`: convert the values of all enum constants to `ulong`, try them one by one from largest to smallest, subtract out the bits that matched, and finally list the corresponding names ordered by ascending value.
