### ISSUE TITLE
Cannot search for methods by name

### ISSUE THREAD

**Issue by paulpach** [dotnet/docfx#5695]
**Operation System**: `MacOS`

**DocFX Version Used**: 2.48.1.0

**Template used**: `templates/material`

**Steps to Reproduce**:
1.  create docfx project 
2. add _enableSearch to docfx.json
3. `docfx metadata docfx.json`
4. `docfx build docfx.json --serve`
5. open docs in brower
6. search for a method name
7. No class with that method is found

As a life demo of the problem:
1. go to https://mirror-networking.com/docs/
2. at the top right search for "ReplacePlayerForConnection"
3. It finds "Custom Character Spawning" and "Change Log"
4. Now search for "ReplacePlayerForConnection(NetworkConnection"
5. It finds "Class NetworkServer"
6. I expect "Class NetworkServer" to show in step 3

the docfx project source can be found at:  https://github.com/vis2k/Mirror/tree/master/doc

**Expected Behavior**:
I expect to find the classes that have a method with the provided name

**Actual Behavior**:
It does not find the class unless I add `method(<first parameter type>` or `method*`
My users have no clue they have to search for that
full text search should match with just the method name.

**Comment by schnebi** [comment]
Hi there,
this is a Problem since 2017. In the issue #2048 it has already been discussed and there is, as much as i know, no improvement on that. The search for Methods, at least in my project, is a big part of the documentation and needs more attention. It would be great if it can be fixed in the near future.
