### ISSUE TITLE
Problem finding Methods in Search funktion

### ISSUE THREAD

**Issue by schnebi** [dotnet/docfx#5892]
Operation System`Windows`
DocFX Version Used : 2.52

Template used: custom same problem with default

Steps to Reproduce:

Search for a Method (in my example i actually use the official Docfx Dokumentation as it does not work there aswell.

![Step 1](https://user-images.githubusercontent.com/65154326/81533757-08fe0080-9367-11ea-9668-65d334757710.PNG)
 I want to search for the Postbuild method in this case

![Step 2](https://user-images.githubusercontent.com/65154326/81533959-6e51f180-9367-11ea-9d8e-ef597999f005.PNG)

There are hits yes but non of them link me to the actual class.

With a * in the end i get to the class at least but the Method itself doesnt get highlighte as it should.

![Step 3](https://user-images.githubusercontent.com/65154326/81534123-c983e400-9367-11ea-9703-55a45bf0ce2f.PNG)

![Step 4](https://user-images.githubusercontent.com/65154326/81534195-e8827600-9367-11ea-8268-59e1f5e6d18a.PNG)

This case only seems to be the be true if the Method needs Parameters in this instance (ImmutableList<FileModel>, IHostService). 

If there are no Parameters it is no problem to find the Methode.

![Step 5](https://user-images.githubusercontent.com/65154326/81534405-46af5900-9368-11ea-957f-423c8837d7cb.PNG)

![Step 6](https://user-images.githubusercontent.com/65154326/81534491-6c3c6280-9368-11ea-8012-67c0cbc47668.PNG)

Is this a bug or is there anyway i can tune my searchworker to handle a search like this.

**Comment by Daniel618** [comment]
Hi,

I suspect this issue is valid for the complete search function and not only when searching for methods. When searching you get typeahead suggestions after typing a couple of letters but if you continue typing the suggestions dissappear. After a few more letters suggestions can return but can be completely different.

Example: Typing "Attribute" in the search box:

- Attr -> returns result
- Attri -> No results found
- Attribut -> different result found

![attr](https://user-images.githubusercontent.com/15671805/81783607-e18c6c80-94fb-11ea-8d60-f4cb681b3453.png)

![attri](https://user-images.githubusercontent.com/15671805/81783653-efda8880-94fb-11ea-85a0-15e7fb8f8cbe.png)

![attribut](https://user-images.githubusercontent.com/15671805/81783666-f406a600-94fb-11ea-8d4c-76db38e83174.png)

**Comment by schnebi** [comment]
Hi,
So as i interpret it, it seems like a bug.
I cant imagine that that is the intended way for a search function to operate.
Maybe @superyyrrzz can help out here and clarify things.

**Comment by schnebi** [comment]
Fixed by @paulpach. #5961
Thanks
