### ISSUE TITLE
Visual Studio Build Errors 

### ISSUE THREAD

**Issue by sduffy77** [dotnet/docfx#6413]
**Operating System**:  Windows 10

**DocFX Version Used**: 2.56.2

**Template used**:  default

**Steps to Reproduce**:

1. Pull down docfx.console from NuGet and add it to an existing project which contains multiple target platforms (ie <TargetFrameworks>net461;net48;netstandard2.1</TargetFrameworks> )
2. Configure the docfx.json to only build documentation for netstandard2.1 
      "properties": {
        "TargetFramework": "netstandard2.1"
      }
3. Build the solution

**Expected Behavior**: The documentation would only build for the netstandard2.1 framework.

**Actual Behavior**: It appears from the output window that docfx is being run for each framework and causing an IO error attempting to access the log file.
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3713	The file "obj\Debug\net48\Vasont.Inspire.SDK.AssemblyInfo.cs" could not be created. The process cannot access the file 'E:\Projects\Vasont GIT\Vasont.Inspire.SDK\src\obj\Debug\net48\Vasont.Inspire.SDK.AssemblyInfo.cs' because it is being used by another process.	Vasont.Inspire.SDK	C:\Program Files\dotnet\sdk\3.1.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets	136	

** Additional Info**: I was able to work around by adding the following conditions to the Package Reference in the csproj file:
    <PackageReference Include="docfx.console" Version="2.56.2" Condition="'$(TargetFramework)' == 'netstandard2.1' AND '$(Configuration)' == 'Release'">
however this has an unfortunate side effect, with the conditions added to the package reference it no longer shows up in nuget manager as being installed for the project

**Comment by KalleOlaviNiemitalo** [comment]
> 2. Configure the docfx.json to only build documentation for netstandard2.1
> ```json
> "properties": {
>   "TargetFramework": "netstandard2.1"
> }
> ```

I think that still runs DocFX for each target framework but uses netstandard2.1 in each inner build.

> It appears from the output window that docfx is being run for each framework and causing an IO error attempting to access the log file.

docfx.console.targets sets the `LogFile` property here: <https://github.com/dotnet/docfx/blob/56250e19a7fa546abb7c76d5ae4041c528bc4c2b/src/nuspec/docfx.console/build/docfx.console.targets#L9>

If DocFX is being run multiple times in parallel, then those log files will clash. Perhaps that should be something like `$(IntermediateOutputPath)docfx.log` instead, although I'm not sure `$(IntermediateOutputPath)` is set before that is evaluated.

> Error MSB3713 The file "obj\Debug\net48\Vasont.Inspire.SDK.AssemblyInfo.cs" could not be created.

That seems to be a different problem, not the DocFX log file.

> I was able to work around by adding the following conditions to the Package Reference in the csproj file:

I don't see the conditions on GitHub.

What if, instead of setting a `TargetFramework` property in `docfx.json`, you did this in the project file:

```xml
<PropertyGroup>
  <BuildDocFx Condition="$(TargetFramework) != 'netstandard2.1'">false</BuildDocFx>
</PropertyGroup>
```

i.e. kept the docfx.console package reference, but disabled its targets for every target framework except one?

**Comment by sduffy77** [comment]
Great idea. I like this much better than the workaround I came up with. I added the condition of only building docs in Release
`  <PropertyGroup>
    <BuildDocFx Condition="$(TargetFramework) != 'netstandard2.1' OR '$(Configuration)' != 'Release'">false</BuildDocFx>
  </PropertyGroup>`
