### ISSUE TITLE
Fails to serve on linux

### ISSUE THREAD

**Issue by clayrisser** [dotnet/docfx#7206]
**Operating System**: Linux (Debian)

**DocFX Version Used**: 3.0.0-beta1.804+90e456a78d

**Template used**: default

**Steps to Reproduce**:

1. install docfx on linux [linux.zip](https://github.com/dotnet/docfx/releases/download/3.0.0-beta1.804%2B90e456a78d/docfx-linux-x64-3.0.0-beta1.804+90e456a78d.zip)
2. clone [docfx-seed](https://github.com/docascode/docfx-seed)
3. serve `docfx serve --port 8000`

![Screenshot from 2021-03-16 10-54-13](https://user-images.githubusercontent.com/6234038/111340257-78f3ac00-8646-11eb-8fc0-b921c75f4935.png)

**Expected Behavior**: It should serve docfx on linux

**Actual Behavior**: The server fails to work

![Screenshot from 2021-03-16 10-53-56](https://user-images.githubusercontent.com/6234038/111340225-72653480-8646-11eb-9768-68a2c694d0d5.png)

**Comment by yufeih** [comment]
The issue was reported using v3. Now that we've [stopped supporting v3 for community usage](https://github.com/dotnet/docfx/discussions/8277#discussioncomment-4409645), we've released [v2.60.0](https://github.com/dotnet/docfx/discussions/8334) which runs on .NET Core with support for MacOS and linux, it should fix the serve problem with the new AspNet.Core based server.
