### ISSUE TITLE
breaking: v2.57

### ISSUE THREAD

**Issue by bart-degreed** [dotnet/docfx#7286]
v2.57 breaks our documentation website. 2.56.7 works properly.

![image](https://user-images.githubusercontent.com/54280078/114206597-cae4d480-995b-11eb-823a-7b47f12fb630.png)

![image](https://user-images.githubusercontent.com/54280078/114206872-0f707000-995c-11eb-963d-09b92a899f1e.png)

To repro, clone the repo at https://github.com/json-api-dotnet/JsonApiDotNetCore and run:

```bash
choco install docfx -y
npm install -g httpserver

cd docs
pwsh build-dev.ps1
```

**Comment by TaranbirBhullar** [comment]
We see this issue as well. 

Our setup involves using the DocFx task in azure pipelines, currently breaking our CI.
I would recommend that we allow to use **different versions** in that task to build in case this happens again.

We are now using manual deploy to re-enable this.

Please let us know the ETA on this fix.

**Comment by VladimirRybalko** [comment]
This is a global issue. Even an [official DocFx web site](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html) is broken. 
@superyyrrzz could you please have a look and give us the ETA?

**Comment by jamesmcroft** [comment]
Dang, thought this was something I had done but came around just to check if it was affecting others.

**Comment by superyyrrzz** [comment]
Acknowledged. We will fix it soon. ETA targets 4/12.

**Comment by superyyrrzz** [comment]
@v-pegao @shanluo911

**Comment by superyyrrzz** [comment]
Still investigating. The issue happened because we upgraded bootstrap from 3.4 to 4.6, but it has some changes that break the theme.

The bootstrap upgrade is to fix security issues in dependent packages. We tried reverting the upgrade to test if the security issues persists. We need to wait for next security scan (CG) result to see if it is good.

**Comment by jamesmcroft** [comment]
Thanks for all the updates on this @superyyrrzz, it's appreciated 😄

**Comment by superyyrrzz** [comment]
Fixed in 2.57.1

**Comment by bjorhn** [comment]
Thanks for the quick fix!

Would it be possible to mark 2.57.1 as latest? I'm not sure about how others have their build systems set up, but mine is set up to download the latest release.

**Comment by MortenRei** [comment]
> Thanks for the quick fix!
> 
> Would it be possible to mark 2.57.1 as latest? I'm not sure about how others have their build systems set up, but mine is set up to download the latest release.

Same here. We had to temporarily change our install from "choco install docfx -y" to "choco install docfx -y -version 2.56.7" in our Azure Pipeline. Would be good if 2.57.1 was set at latest, so we could revert this change.

**Comment by DennisSchoutsen** [comment]
Hi, 
The site layout is fixed with the 2.57.1 version. 👍🏻
We experience still an issue with search function, we don't have in a site generated with version 2.56.7.
When entering a keyword in the search bar the site returns the current page and no search results.

This is also true for the DocFX -documentation site ([link](https://dotnet.github.io/docfx/))

do i need to create a new issue for this?

**Comment by bjorhn** [comment]
Works fine now, my build script picked up 2.57.1 after you marked it as latest. Webside renders correctly, too.

Thanks again!

**Comment by jamesmcroft** [comment]
Seems to be working fine now 👍
