### ISSUE TITLE
running on masOS fails loading libhostpolicy.dylib

### ISSUE THREAD

**Issue by cillroy** [dotnet/docfx#7347]
**Operating System**: (`MacOS`)

**DocFX Version Used**: 

**Template used**: (`default`)

**Steps to Reproduce**:

1. dotnet docfx.dll
2. Failed to load //docfx-osx-x64-3.0.0-beta1.894+809d7dd77b/libhostpolicy.dylib, error: dlopen(/docfx-osx-x64-3.0.0-beta1.894+809d7dd77b/libhostpolicy.dylib, 1): no suitable image found.  
3. Did find:
	/docfx-osx-x64-3.0.0-beta1.894+809d7dd77b/libhostpolicy.dylib: code signature in (/docfx-osx-x64-3.0.0-beta1.894+809d7dd77b/libhostpolicy.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
An error occurred while loading required library libhostpolicy.dylib from [/docfx-osx-x64-3.0.0-beta1.894+809d7dd77b/]
@38f9d362daa6 docfx-osx-x64-3.0.0-beta1.894+809d7dd77b % 

**Expected Behavior**:

**Actual Behavior**:

**Comment by eli-darkly** [comment]
I've had no luck getting the pre-built code from https://github.com/dotnet/docfx/releases/download/v2.57.2 to run on either Mac or Linux. I'm a little confused by the reference above to `dotnet docfx.dll`, because the release archive doesn't contain a `docfx.dll`, instead it has `docfx.exe`. But that file doesn't have executable permission and isn't a valid standalone binary; it seems to be an assembly, just as it would be if it were `docfx.dll`. Running an assembly does require the `dotnet` command, but when I do `dotnet docfx.exe` I get the same error about `libhostpolicy` (the only difference being that that's a `.dylib` on MacOS vs. a `.so` on Linux).

Either there's something wrong with the build/release process, or the documentation isn't correct about how to run it. I can run it on a Mac with no problem if I install it with Homebrew, but on Linux there's no option other than using the release archive (or, I guess, building the whole tool from scratch) and unfortunately Linux is the use case I mainly need.

**Comment by yufeih** [comment]
@cillroy , how did you get the binary? Is it downloaded from GitHub pre-releases or via `dotnet install`?

**Comment by eli-darkly** [comment]
Hmm, well, in my Linux testing I was using a .NET 5.0 SDK image, but when I installed Mono and ran it with `mono docfx.exe`... it worked fine. That's good to know but I am a bit confused that 1. it is possible for portable .NET bytecode (as opposed to an executable binary) to only work with the Mono runtime and not with the MS runtime, and 2. that Microsoft themselves would build a tool that way.

I did see that the DocFX documentation said "For macOS/Linux users: Use Mono version >= 5.10" but I thought it meant that's the version of Mono to use _if you don't have the .NET SDK already_. It is not at all clear from the current docs that running via `dotnet` won't work.

**Comment by fikriauliya** [comment]
I encountered the same problem on Mac.

```
> nuget install docfx.console
> dotnet  ~/.nuget/packages/docfx.console/2.58.9/tools/docfx --version
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found
```

But it can run using Mono 
```
mono  ~/.nuget/packages/docfx.console/2.58.9/tools/docfx.exe --version
```

I wonder whether @eli-darkly has found the solution?

**Comment by eli-darkly** [comment]
@fikriauliya Currently, the only solution I'm aware of is either to run it with Mono, or build it from source. The compiled binary simply isn't compatible with the .NET 5.0 runtime; apparently, Mono bytecode is not quite the same thing.

Since my builds run in Docker, I ended up just creating a custom Docker image that is based on the .NET 5.0 SDK image and then installs Mono, which is a slight pain but then at least I can reuse that image instead of having to reinstall Mono all the time. Here's what my Dockerfile looks like (note, in my build process Mono has already been downloaded at that point, but you could download it from inside the Docker build instead of course):

```
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal

# Install Mono - see https://www.mono-project.com/download/stable
RUN apt-get update
RUN apt-get install -y gnupg ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt-get update
RUN apt-get install -y mono-devel

# Copy docfx (already downloaded and unzipped by Makefile)
COPY ./downloads/docfx /root/docfx
ENV PATH="${PATH}:/root/docfx"
```

**Comment by yufeih** [comment]
The [v2.60.0](https://github.com/dotnet/docfx/discussions/8334) release runs on .NET Core with support for MacOS and linux without mono.
