### ISSUE TITLE
Favicon not copied if located in upper folder

### ISSUE THREAD

**Issue by mikasoukhov** [dotnet/docfx#7581]
**Operating System**: Windows

**DocFX Version Used**: 2.58.2

**Template used**: default

**Steps to Reproduce**:

In local docfx.json
1. change build/resource/files relative path to ../favicon.ico
2. set build/globalMetadata/_appFaviconPath to favicon.ico

```
"resource": [
      {
        "files": [
          "images/**",
          "../favicon.ico"
        ],
        "exclude": [
          "obj/**",
        ]
      }
    ],
    "globalMetadata": {
      "_appFaviconPath": "favicon.ico"
    },
```

**Expected Behavior**: favicon from a parent folder should be copied.

**Actual Behavior**: the read favicon not moved and default generated.

**Comment by jamiehankins** [comment]
That's not how it works. You need a `src` on the `resource` object.

**Try this:**
```json
"resource": [
  {
    "files": [
      "images/**"
    ]
  },
  {
    "files": ["favicon.ico"],
    "src": "../"
  }
],
```

**Bonus Content:**
If you want your favicon to actually work and you're using the default template, include the block below:
```json
"globalMetadata": {
  "_appFaviconPath": "favicon.ico"
},
```
**Disclaimer:**
I don't work for Microsoft, and my employer has nothing to do with anything I post here. If I've saved you some time or otherwise made your day better, I'm glad. That's good karma for me. If the opposite is true, then know that I at least tried to help.

**Comment by mikasoukhov** [comment]
That is work!
