### ISSUE TITLE
References to members of external generic types are not resolved

### ISSUE THREAD

**Issue by yevgeni-zolotko** [dotnet/docfx#7656]
With
`"xrefservice": [ "https://xref.docs.microsoft.com/query?uid={uid}" ],`
in docfx.json,

the following reference is resolved successfully:
```<xref:System.Collections.ObjectModel.Collection`1>```
but this one:
```<xref:System.Collections.ObjectModel.Collection`1.Add>```
is not.
However, same-assembly generic type members are resolved successfully:
```<xref:MyNamespace.MyClass`1.MyProperty>```

**Comment by Herrmel** [comment]
The correct uid for Methods need the parametertypes aswell or use a * for any overload. The correct uid should be ``System.Collections.ObjectModel.Collection`1.Add(`0)`` or ``System.Collections.ObjectModel.Collection`1.Add*``. You can find the uid if you inspect the html of the docs page and right above the heading there should be an empty link-Element that contains the uid, but all specialcharacters are replaced with `_`.

**Comment by glopesdev** [comment]
@Herrmel this seems to be broken in newer versions of docfx with automatic resolution of xref to .NET APIs. The `*` syntax fails to resolve and it's unclear from the docs what to replace it with. Any ideas?

**Comment by Herrmel** [comment]
The query itself still works: [xref.docs.microsoft.com/query?uid=System.Collections.ObjectModel.Collection`1.Add*](https://xref.docs.microsoft.com/query?uid=System.Collections.ObjectModel.Collection`1.Add*)
You probably need to open a new issue to reach someone from the team since it seems to be a bug in docfx as far as I can tell.
