### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by Const-me** [dotnet/docfx#7663]
Hi. You’re saying it’s MIT, yet you’re using a third-party DLL itextsharp.dll 5.5.13.1 which is covered by [AGPL](https://www.gnu.org/licenses/agpl-3.0.html).

AGPL license is highly contagious, may even contaminate the content produced by the library.

Could you please fix somehow? For instance, by downgrading to this version: https://www.nuget.org/packages/iTextSharp-LGPL/

**Comment by bitbonk** [comment]
> However, it seems DocFX v3 is nearing release 
I highly doubt that there is still a plan to release v3 _at all_. v3 is solely used for docs.microsoft.com and there hasn't been any sign that they are going to invest in making a community version of it.

**Comment by glopesdev** [comment]
> I highly doubt that there is still a plan to release v3 at all. v3 is solely used for docs.microsoft.com and there hasn't been any sign that they are going to invest in making a community version of it.

Is this true? Would like to hear from the maintainers about what the official stance is regarding the future of DocFX as we are currently considering adopting it for documentation across a large community project.

**Comment by bitbonk** [comment]
I am not a maintainer of DocFX so I can't speak for them but I am an avid user of DocFX since 2017 and can speak about what I have observed.

Version 3 of DocFX has been in development at least [since 2018](https://github.com/dotnet/docfx/commit/6f6285f2bd7bc613645a401c94ccd4b88e871ec1) and is used om docs.microsoft.com [since 2019](https://github.com/dotnet/docs/commit/5dc22c16f537bc7087c012c0068621c3a620927d). 

In the early years the DocFX team was well involved with the community and very helpful and responsive in the GitHub issues and even implemented feature requests made by the community. Especially @vicancy and  @superyyrrzz did an awesome job here!

But at some point the DocFX (probably somewhere around early 2020) team has completely and totally stopped all communication with the community seemingly focusing purely on the need of docs.microsoft.com and the internal development of version 3. The many unanswered issues (not just open issues, but issues with _no response at all_) here on GitHub speak for themselves, the [gitter chat](https://gitter.im/dotnet/docfx) has been completely abandoned by the team and [stackoverflow](https://stackoverflow.com/questions/tagged/docfx) looks equally sad.

That's also when version 2 switched into pure maintenance mode containing only bugfixes and no more new features. As a result version 2 has fallen far behind, still relying on Visual Studio being installed and not supporting newer .NET features such as [C# 9, 10](https://github.com/dotnet/docfx/issues/7191), global tools etc.

There have been many attempts to get an answer about the future of DocFX (e.g. [Twitter](https://twitter.com/bitbonk/status/1271451016043560965?s=21), [GitHub](https://github.com/dotnet/docfx/issues/7050)). The answer was always some "other priorities" bla bla.

So altogether I don't have high hopes for the future of DocFX. 🤷🏻‍♂️

Unfortunately there are not many alternatives for documentation solutions that integrate well with .NET ([Statiq](https://www.statiq.dev/docs) by @daveaglick being the only one I know of) so we are basically stuck with DocFX in its current unsatisfactory condition.

**Comment by lextm** [comment]
@bitbonk Sandcastle is another feasible option. It has been upgraded to support new .NET bits, so I already switched back to that for months.

**Comment by markjulmar** [comment]
Thanks for highlighting this issue - we need to unify the licensing and make sure we aren't pulling in dependencies which don't align to the open-source licensing we are published under. I've assigned this to me to investigate, but if there are other spots you are aware of, please let me know.
