### ISSUE TITLE
Seemed file-scoped namespace not supported?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docfx#7774]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

**DocFX Version Used**:  `2.58.9`

**Template used**: `default`

Sample GitHub action build: https://github.com/WeihanLi/WeihanLi.Npoi/runs/4574658039?check_suite_focus=true

**Comment by JeremyCaney** [comment]
As with the lack of support for global `using` directives—another new C# 10 feature that’s not yet supported (see #7737)—this can worked around by sourcing your API `metadata` from the compiled assemblies instead of the project files or source code. 

Unfortunately, in doing so, you unfortunately lose the “View Source” link (see #7816).

**Comment by MrDave1999** [comment]
I'm using file-scoped namespace in a project and I didn't have any problem, in fact, it even generated the "View Source" link. Although the version of docfx I used was `2.59.4`. Try with this version and import the types with the using directive

**Comment by yufeih** [comment]
File-scoped namespace was supported in the latest version of docfx. See [this as an example](https://github.com/dotnet/docfx/blob/main/samples/seed/src/DotnetNew/CSharp10.cs)
