### ISSUE TITLE
xrefService for the Roslyn API

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/docfx#7973]
I am documenting an API extending that references the Roslyn API. 

I may have stated my the tickettitle incorrectly and it may be unrelated with xref service. 

I am getting the following warning and I don't know what to do about it):

Warning:[MetadataCommand.ExtractMetadata]Invalid cref value "!:Diagnostic" found in triple-slash-comments for ReportDiagnostic defined in ...

**Comment by KalleOlaviNiemitalo** [comment]
The compiler generates `cref="!:Diagnostic"` if an XML documentation comment has `cref="Diagnostic"` and the compiler does not understand what that refers to, e.g. because you the source file does not contain the correct `using` directive, or because the correct reference assembly is not being used.

If DocFX runs MSBuild incorrectly somehow and that causes MSBuild not to find the correct reference assembly, you can generally work around that by running MSBuild separately and feeding the generated \*.dll and \*.xml files to DocFX, i.e. don't mention any \*.csproj files in docfx.json at all.

**Comment by gfraiteur** [comment]
Thank you. This helped me solving the issue by referencing directly the dll.
