### ISSUE TITLE
DefineConstants / MSBuild Properties not working with non-csproj configurations.

### ISSUE THREAD

**Issue by Lachee** [dotnet/docfx#8028]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows

**DocFX Version Used**: 
- docfx 2.44.0.0
- docfx 2.59.2.0

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:
_Via Example_
1. `git clone https://github.com/Lachee/docfx-define-constants-issue.git` - Repository highlighting issue
2. `cd docfx-define-constants-issue`
3. `docfx Documentation/docfx.json`

**Expected Behavior**:
The `DefineConstants` property gets applied to the `MSBuild` and classes within a `#if` condition have their documentation generated

**Actual Behavior**:
Anything within a `#if` gets ignored.

**Other**:

I have generated a sample project that experiences the issue here: https://github.com/Lachee/docfx-define-constants-issue but the main project that has an issue is my [Unity Utilities](https://github.com/Lachee/unity-utilities). It is a Unity Package so doesnt directly have .csproj itself.

Here is the metadata i used
```json
    "metadata": [
        {
            "src": [
                {
                    "src": "..",
                    "files": [ "Scripts/**/*.cs" ]
                }
            ],
            "globalNamespaceId": "Global",
            "dest": "api",
            "properties": {
                "DefineConstants": "SOME_DEFINE=1"
            }
        }
    ],
```

**Comment by KalleOlaviNiemitalo** [comment]
`SOME_DEFINE=1` is odd because C# conditional compilation defines cannot have values.

That said, the DocFX implementation looks like it uses Roslyn directly, rather than MSBuild, if you specify `*.cs` files rather than `*.csproj`. If you don't have a project, then there's no SDK that would translate the MSBuild property to [CSharpParseOptions.PreprocessorSymbolNames](https://docs.microsoft.com/dotnet/api/microsoft.codeanalysis.csharp.csharpparseoptions.preprocessorsymbolnames?view=roslyn-dotnet-4.2.0). Perhaps DocFX could be changed to recognize the `DefineConstants` name, construct a CSharpParseOptions instance with the corresponding settings, and pass that to [SyntaxFactory.ParseSyntaxTree](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntaxfactory.parsesyntaxtree?view=roslyn-dotnet-4.2.0#microsoft-codeanalysis-csharp-syntaxfactory-parsesyntaxtree(microsoft-codeanalysis-text-sourcetext-microsoft-codeanalysis-parseoptions-system-string-system-threading-cancellationtoken)) via CompilationUtility.CreateCompilationFromCsharpCode:

<https://github.com/dotnet/docfx/blob/9a3c8aa16adec1be4ee2e62ef45a9a0c78ccef14/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadataWorker.cs#L309>

<https://github.com/dotnet/docfx/blob/9a3c8aa16adec1be4ee2e62ef45a9a0c78ccef14/src/Microsoft.DocAsCode.Metadata.ManagedReference/ExtractMetadata/CompilationUtility.cs#L27>

**Comment by KalleOlaviNiemitalo** [comment]
[`CodePage`](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/advanced#codepage) might affect metadata, if you have non-ASCII characters in identifiers or string literals. [`AllowUnsafeBlocks`](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/language#allowunsafeblocks) and [`LangVersion`](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/language#langversion) might also be needed, depending on what the defaults are in Roslyn (as opposed to the .NET SDK).

If one needs item types like [`Reference`](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/inputs#references), I think one should just set up a C# project file that configures those for DocFX, even if that project won't ever be built for other purposes. I don't think DocFX itself should configure references for Roslyn.

**Comment by Lachee** [comment]
Is there any update with this? This is a breaking issue for my documentation as it literally stops be from generating half the documentation.

**Comment by yufeih** [comment]
Is it a unity specific problem? It seems most ordinary .NET projects uses `csproj` , what is the equivalence in the unity world? In another word, how do you specify `SOME_DEFINE=1` in a unity project?

**Comment by yufeih** [comment]
Also assembly name #4597

**Comment by Lachee** [comment]
> Is it a unity specific problem? It seems most ordinary .NET projects uses `csproj` , what is the equivalence in the unity world? In another word, how do you specify `SOME_DEFINE=1` in a unity project?

Unity defines the [scripting symbols](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) itself when compiling.

Newer versions of Unity [uses Roslyn to compile](https://docs.unity3d.com/Manual/CSharpCompiler.html).

Unity generates the `csproj` in the root level of the project, per [assembly definition](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html), so packages don't actually contain their own `csproj`. It cannot be expected for Packages to maintain a csproj themselves or to include the root level ones generated by unity.

**Comment by GasimoCodes** [comment]
For anyone here in the future, to set a symbol (for instance: #if TIMELINE_PRESENT), you can just use add

```json
      "properties": {
        "DefineConstants": "TIMELINE_PRESENT"
      }
```

into src under your docfx configuration metadata. After adding, it finally found and documented all my code which used this symbol!

**Comment by Lachee** [comment]
> For anyone here in the future, to set a symbol (for instance: #if TIMELINE_PRESENT), you can just use add
> 
> ```json
>       "properties": {
>         "DefineConstants": "TIMELINE_PRESENT"
>       }
> ```
> 
> into src under your docfx configuration metadata. After adding, it finally found and documented all my code which used this symbol!

so this issue has been fixed? This only worked if there was a included csproj as per the original issue.

**Comment by yufeih** [comment]
> > For anyone here in the future, to set a symbol (for instance: #if TIMELINE_PRESENT), you can just use add
> > ```json
> >       "properties": {
> >         "DefineConstants": "TIMELINE_PRESENT"
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > into src under your docfx configuration metadata. After adding, it finally found and documented all my code which used this symbol!
> 
> so this issue has been fixed? This only worked if there was a included csproj as per the original issue.

Not this isn't supported yet for building .cs files directly.
