### ISSUE TITLE
Unable to genertate documents from C++ projects

### ISSUE THREAD

**Issue by VinOuO** [dotnet/docfx#8096]
**Operating System**: Wildows powershell

**DocFX Version Used**:  2.59.2.0

**Template used**: discordfx

**Steps to Reproduce**:

1. put a .yaml file converted from a .xml file generated from docxygen (for a C++ project) 
2. execute docfx

**Expected Behavior**:
I expected docfx to generate the html file for me; like it did when I was trying to generate documents from a C# project.

**Actual Behavior**:
a Warning came out saying .yaml are not supported.

**Question**:
Is it possible for me to genetate documents for C++ projects using docfx?
[https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html](https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html)
The link above says I can do it by:
1. converting the C++ project to .xml files using docxygen
2. then convert it to .yaml files 
3. using the .yaml files, I can finally genetate C++ documents 

Am I missing any steps or did I do something wrong?

p.s.
Thanks for your time :)

**Comment by paulushub** [comment]
@VinOuO First, the link to the multiple language support page is wrong (the link text is OK).
What is the error in this case?

**Comment by VinOuO** [comment]
May I ask, in the docfx.json file:
![image](https://user-images.githubusercontent.com/74755998/178658899-3bec68a4-7980-4383-be00-000aebf0f535.png)
what's the different between the .md files and the .yml files put in those two "files" sessions?

From what I am awared of, the .yml files tell docfx the structures of the pages, while the .md files are converted to .html pages

But I don't get why the toc.yml
![image](https://user-images.githubusercontent.com/74755998/178658642-50155cef-1671-404d-b3a7-87141d77ef5e.png)
which appears to be the root to all .yml files should be in the second "files", while the api/*.yml file should be in the filrst "files"

**Comment by paulushub** [comment]
@VinOuO For your questions, have you gone through the tutorials or Walkthrough Topics?

https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_create_a_docfx_project.html

Also, can you create a single file C++ sample to demonstrate your configuration?

**Comment by VinOuO** [comment]
Hello dear @paulushub,

I had read it before, but I must have confused during my survey on the internet.
I read the tutorials again, and the following is what I current acknowledge.
Could you kindly confirm it for me?

So the following is my current docfx.json. I most have messed it up during my survey. But I think I get it now.
The comment at the right of the picture is my corrent believe.
![image](https://user-images.githubusercontent.com/74755998/179140555-496594ca-0bf2-49c5-89da-9a90c08c9b0c.png)
![image](https://user-images.githubusercontent.com/74755998/179141487-93aeece9-5956-43e5-adc5-a99547a99ff4.png)

As you may notice, the project is a C# project, because I have both C# & Cpp projects going on, and I figured I should have more understanding about how docfx works before I go advance.

Thanks again for your help :)

**Comment by paulushub** [comment]
@VinOuO I am also not an expert on docfx, so just using this opportunity to learn.
Some hints that might help
* **metadata** This section is not required for a documentation. So, your documentation definition will be the **build** section.
* If you need to create the metadata, from say the C# projects or `dll/xml` then you need it, otherwise; you can delete it.
* If you create the **metadata** section, the **dest** (say, `"api"`) will be the output of the metadata. This will then be used to define the build content in the **build** section (say `"api/*.yml"`).
* Since your documentation includes both C# and C++ projects; use the **metadata** section to generate the `*.yml` for your C# and your own tools to generate `*.yml` for the C++.
* Specify the combined content for your documentation in the **build** section
    - **"api/*.yml**  // for the C#
    - **"cpp/*.yml**  // for the C++
* Note that both **metadata** and **build/content** are lists, so you can define several of them for your needs.
* Also, support for other languages (besides C# and VB) requires UniversalReferenceDocumentProcessor, https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html

Working on a sample to demonstrate your use case (was hoping you will post a sample for testing).

**Comment by VinOuO** [comment]
> @VinOuO I am also not an expert on docfx, so just using this opportunity to learn. Some hints that might help

@paulushub 
Really?! I though you were an R&D in Microsoft, haha.

If not so, thanks you sooo much for your kind replies.
They sure do help a lot.
I will continue to study.
Thanks for the infos again!

Have a nice day :)
