### ISSUE TITLE
V3 does not output csproj api doc files and HTML output is empty

### ISSUE THREAD

**Issue by mikernet** [dotnet/docfx#8234]
**Operating System**: `Windows`

**DocFX Version Used**: 3.0.0-beta1.1260+9e3c31b73d

**Template used**: `default` 

**Steps to Reproduce**:

1. Try to build docs at https://github.com/Singulink/Singulink.IO.FileSystem/tree/master/Docs

**Expected Behavior**:

Should output docs for the referenced csproj project like V2 does. 

**Actual Behavior**:

The `/api` folder, which is set as the `dest` for the csproj, does not contain any output files after build. It should be generating the `toc.yml` file (among others) the console output is complaining is missing. It works using V2. Removing all but the default template from the `docfx.json` config does not make a difference. The html files in the `_site` output are empty.

This is the build console output:

```
PS C:\Projects\SL\Singulink.IO.FileSystem\Docs> docfx build --verbose
docfx: 3.0.0-beta1.1260+9e3c31b73d
Microsoft.Docs.Validation: 1.0.0+9f7d525f9707f0a0ebf5d3e9565bb500867f700b
ECMA2Yaml: 1.0.0+61b4c05b4de78e69851b45153dd2f32828006b76
Loading docsets...
Repository https://github.com/Singulink/Singulink.IO.FileSystem#master at committish: 63905e4a6e05546b182ea84d2fe37b198bbbaff7
Loading config...
Restoring dependencies...
Restoring packages done in 13.79ms
Restoring files done in 13.63ms
Loading git commits done in 27.98ms
Failed to get AAD access token<Prod>
Building...
Loading redirections done in 5.84ms
Globing files done in 32.61ms
Building publish url map done in 59.67ms
toc-not-found ./toc.yml(4,9): Unable to find either toc.yml or toc.md inside api/ Please make sure the file exists.
Loading TOC done in 144.5ms
file-not-found ./articles/advanced/pathoptions-handling.md(7,44): Invalid file link: '../../api/Singulink.IO.PathOptions.yml'.
Loading redirection history done in 0.19ms
Building xref map done in 1.46ms
Loading xref map done in 10.49ms
liquid-not-found ./articles/advanced/pathoptions-handling.md(1,1): Liquid template 'Conceptual.html.liquid' not found for mime type 'Conceptual', the output HTML will not be generated.
liquid-not-found ./articles/system.io/exception-handling-differences.md(1,1): Liquid template 'Conceptual.html.liquid' not found for mime type 'Conceptual', the output HTML will not be generated.
liquid-not-found ./articles/guides/getting-started.md(1,1): Liquid template 'Conceptual.html.liquid' not found for mime type 'Conceptual', the output HTML will not be generated.
liquid-not-found ./articles/system.io/problems-with-system-io.md(1,1): Liquid template 'Conceptual.html.liquid' not found for mime type 'Conceptual', the output HTML will not be generated.
liquid-not-found ./api/index.md(1,1): Liquid template 'Conceptual.html.liquid' not found for mime type 'Conceptual', the output HTML will not be generated.
liquid-not-found ./index.md(1,1): Liquid template 'Conceptual.html.liquid' not found for mime type 'Conceptual', the output HTML will not be generated.
Building 10 files done in 287.36ms
Convert Legacy Manifest done in 39.63ms
Convert Legacy Dependency Map done in 13.01ms
Convert Legacy File Map done in 37.85ms
Converting to legacy done in 98.36ms
```

**Comment by VaclavElias** [comment]
I am not sure if it is possible with `docfx.json` but I had to figure out another steps to generate API Docs... I haven't had time to write those steps just yet to some useful and helpful blog post..

Check this https://github.com/dotnet/docfx/discussions/8227.

I apologise, just some messy hints:

I used this https://github.com/mono/api-doc-tools/releases/tag/mdoc-5.9.1 to generate xml files `d:\mdoc\mdoc update -o en -fx frameworks\CatLibrary --use-docid`

There need to be some file `frameworks.xml` which I found here https://github.com/docascode/ECMA2Yaml/tree/develop/test and created similar folder structure..

At the end docfx v3 generates yaml from those xml files and then docfx v3 generates html files from those yaml files automatically..

This is my test `docfx.yml` which I use instead of `docfx.json`.  `monodoc` and `monikerDefinition` must be provided if you generate API Docs..

```
template: https://github.com/VaclavElias/template.git
defaultLocale: ''
blogUrl: "/blog/"
paginate: 2
exclude: [
    "README.md","en/*.*"
]
monodoc:
  - id: v1
    sourceXmlFolder: "en"
    outputYamlFolder: "api"
monikerDefinition:
  monikers:
    - moniker_name: cat-1.0
globalMetadata:
  titleSuffix: My Awesome Website
  menu_path: "/toc.json"
```

I still need to figure out some bits, e.g. why it generated the docs to this weird folder, probably there is another settings option to set it..

<img width="464" alt="image" src="https://user-images.githubusercontent.com/4528464/199367736-f2192c63-0643-4716-8d6f-48ced92df291.png">

**Comment by mikernet** [comment]
Um, ok, I'm clearly confused then. I thought I saw something months ago of people successfully using just docfx v3 to output HTML .NET API docs, but it seems I'm mistaken. I feel like DocFX v3 is the Half-Life 3 of doc engine releases, haha. Had some extra time so wanted to start migrating and testing my v2 theme but if v3 is nowhere near done then I'll just hold off for now.

**Comment by VaclavElias** [comment]
Let's wait if someone can confirm my comments above :)

**Comment by yufeih** [comment]
> why it generated the docs to this weird folder

That one is the version hash code, we haven't got .NET API fully working yet.
