### ISSUE TITLE
Example code rendering doesn't preserve indentation

### ISSUE THREAD

**Issue by pepone** [dotnet/docfx#8720]
**Describe the bug**

Example code rendering doesn't preserve indentation or empty lines.

**To Reproduce**

You can use the test project from https://github.com/pepone/docfx-example-code-rendering-test

**Expected behavior**

The code indentation and empty lines should be rendered

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.66.2+95d113dca43efe17044f80b056b40789bd6a65db

**Additional context**

<img width="1282" alt="docfx-example-code" src="https://user-images.githubusercontent.com/254604/236165985-91e82d7b-507b-4b23-aea4-47cd7f8aab14.png">

**Comment by pepone** [comment]
A simple alternative/workaround here is to provide the example using a file overwrite.

**Comment by paulushub** [comment]
see the seed sample:
https://github.com/dotnet/docfx/blob/6d80b632e03b198af8031bad77ae5ff4ff3c0fa2/samples/seed/dotnet/project/Project/Class1.cs#L52

**Comment by yufeih** [comment]
I can repro this. The problem has to do with the `<para>` tag before the `<code>` tag. As a workaround, add a blank line before `<code>` tag :

```
/// <para>...
///
/// <code ...>
```

**Comment by yufeih** [comment]
This is the known side effect of parsing XML comment as markdown. It can be resolved by:
- Keep using markdown syntax and adding a blank line before a `<code>` tags
- Turn off markdown parsing by setting [`{"shouldSkipMarkup": true}`](https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#supported-xml-tags)

The reason we need blank line between `<code>` and `<para>` in markdown mode is because common mark treats an empty line as end of HTML block marker unless the HTML block starts with a code block. Without the blank line, a code chunk with >4 indentation before a blank line is treated as a markdown code fence, creating a nested code block.

**Comment by yufeih** [comment]
It isn't about referencing code from another file, see [this markdown demo](https://spec.commonmark.org/dingus/?text=%3Cp%3E%3C%2Fp%3E%0A%0A%3Cpre%3E%3Ccode%3E%0A%7B%0A%0A%20%20%20%20right%0A%0A%7D%3C%2Fcode%3E%3C%2Fpre%3E%0A%0A%3Cp%3E%3C%2Fp%3E%0A%3Cpre%3E%3Ccode%3E%0A%7B%0A%0A%20%20%20%20wrong%0A%0A%7D%3C%2Fcode%3E%3C%2Fpre%3E) on how new line affects rendering of HTML blocks
