### ISSUE TITLE
[Bug] Invalid documentation on type parameter

### ISSUE THREAD

**Issue by bkoelman** [dotnet/docfx#9755]
**Describe the bug**
When a generic class contains a summary, but the type parameter is not documented, the summary text is shown for the type parameter.

**To Reproduce**
1. Create a new project and add the following class:
    ```c#
    /// <summary>
    /// A visitor for tree nodes.
    /// </summary>
    public sealed class NodeVisitor<T>
    {
    }
    ```
2. Follow the getting-started steps from the docfx documentation.
3. Open the documentation website in the browser.

    ![image](https://github.com/dotnet/docfx/assets/10324372/707b9a1e-9142-4723-bbd8-1e84d54c9440)

**Expected behavior**
No documentation should be shown for the type parameter, because it is not documented. This worked properly in v2.74.0:

![image](https://github.com/dotnet/docfx/assets/10324372/21ca9d40-8ba2-4e1c-97a4-c4cc11ab4d77)

**Context (please complete the following information):**
- OS: Windows 11
- Docfx version: latest master (at commit 1d5e946ff3f761e91df640f231729df428f1283c)
- .NET version: .NET 8
- `docfx.json` config: default settings produced by `docfx init`

**Comment by filzrev** [comment]
This issue seems occurred from [docfx v2.75.1](https://github.com/dotnet/docfx/releases/tag/v2.75.1)

It can be fixed by adding following lines to [templates/common/ManagedReference.common.js] file. (https://github.com/dotnet/docfx/blob/main/templates/common/ManagedReference.common.js#L199-L207)

```javascript
  if(vm.syntax.typeParameters) {
    vm.syntax.typeParameters.forEach(item => {
      item.description = item.description || "";
    });
  }
```

or explicitly assign empty string to `Description` property at [ApiParameterBuildOutput.cs](
https://github.com/dotnet/docfx/blob/f0864a918460dd80aec5b16b5ee28b6c27c72953/src/Docfx.Build.ManagedReference/BuildOutputs/ApiParameterBuildOutput.cs#L30-L57)
