### ISSUE TITLE
[Feature Request] Additional Schemas

### ISSUE THREAD

**Issue by JM2K69** [dotnet/docfx#9980]
I have created two more **YamlMine schema** like `Dashboard`. Where can I push them ? @yufeih 
https://github.com/dotnet/docfx/blob/092b267abf9da13abbebd7b08f587902c5f3404e/docs/template/schemas/Dashboard.schema.json

**Comment by yufeih** [comment]
The Dashboard was there because [this page](https://dotnet.github.io/docfx/extensions/templates.html) needs it. That template is not shipped as part of the product.

If you would like to share your schemas and templates to be useful to others, we can create a new "Content Templates" page [here](https://github.com/dotnet/docfx/blob/main/docs/extensions/toc.yml) and link to your work.
